/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;
import Persistencia.modelTemp.ModelUser;
import Services.RedefinirSenhaService;
import Visao.Components.SimpleForm;
import Visao.JframeManager.FormManager;
import Visao.Utils.MessagesAlert;

import javax.swing.*;


/**
 *
 * @author john
 */
public class FormEsqueciSenha extends SimpleForm {

    /**
     * Creates new form formLogin
     */
    public FormEsqueciSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pLogin = new javax.swing.JPanel();
        pEsquerda = new javax.swing.JPanel();
        tfLogin = new javax.swing.JTextField();
        lbLogin = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btEntrar1 = new javax.swing.JButton();
        pDireita = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setLayout(new java.awt.BorderLayout());

        pLogin.setBackground(java.awt.SystemColor.controlHighlight);
        pLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 1, true));
        pLogin.setMaximumSize(new java.awt.Dimension(800, 400));
        pLogin.setMinimumSize(new java.awt.Dimension(800, 400));
        pLogin.setPreferredSize(new java.awt.Dimension(800, 400));
        pLogin.setLayout(new java.awt.GridLayout(1, 2));

        pEsquerda.setBackground(new java.awt.Color(255, 255, 255));
        pEsquerda.setMaximumSize(new java.awt.Dimension(400, 400));
        pEsquerda.setMinimumSize(new java.awt.Dimension(400, 400));
        pEsquerda.setPreferredSize(new java.awt.Dimension(400, 400));

        tfLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbLogin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbLogin.setText("Digite seu email:");

        btEntrar.setBackground(new java.awt.Color(0, 102, 102));
        btEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btEntrar.setText("Próximo");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lbTitulo.setText("Esqueci a Senha");

        btEntrar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEntrar1.setForeground(new java.awt.Color(0, 0, 0));
        btEntrar1.setText("Voltar ao Login");
        btEntrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEsquerdaLayout = new javax.swing.GroupLayout(pEsquerda);
        pEsquerda.setLayout(pEsquerdaLayout);
        pEsquerdaLayout.setHorizontalGroup(
            pEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEsquerdaLayout.createSequentialGroup()
                .addGroup(pEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEsquerdaLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lbTitulo))
                    .addGroup(pEsquerdaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLogin)
                            .addGroup(pEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pEsquerdaLayout.createSequentialGroup()
                                    .addComponent(btEntrar1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btEntrar))
                                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pEsquerdaLayout.setVerticalGroup(
            pEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEsquerdaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbTitulo)
                .addGap(67, 67, 67)
                .addComponent(lbLogin)
                .addGap(18, 18, 18)
                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(pEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntrar1)
                    .addComponent(btEntrar))
                .addGap(39, 39, 39))
        );

        pLogin.add(pEsquerda);

        pDireita.setBackground(new java.awt.Color(0, 102, 102));
        pDireita.setMaximumSize(new java.awt.Dimension(400, 400));
        pDireita.setMinimumSize(new java.awt.Dimension(400, 400));
        pDireita.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel2.setFont(new java.awt.Font("Noto Sans CJK HK", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Copyright©Clínica Cpan. Todos os direitos reservados.");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/cpan-small.png"))); // NOI18N

        javax.swing.GroupLayout pDireitaLayout = new javax.swing.GroupLayout(pDireita);
        pDireita.setLayout(pDireitaLayout);
        pDireitaLayout.setHorizontalGroup(
            pDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDireitaLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(pDireitaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDireitaLayout.setVerticalGroup(
            pDireitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDireitaLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(111, 111, 111)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );

        pLogin.add(pDireita);

        add(pLogin, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrar1ActionPerformed
        FormManager.logout();
    }//GEN-LAST:event_btEntrar1ActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {
        String email = tfLogin.getText().trim();
        try {
            RedefinirSenhaService redefinirSenhaService = new RedefinirSenhaService();

            // Descobre o tipo de usuário com base no email
            String tipoUsuario = redefinirSenhaService.descobrirTipoUsuario(email);

            // Gera o token para esse email e tipo de usuário
            redefinirSenhaService.gerarTokenRedefinicao(email);

            // Vai para a próxima tela sem precisar do token, apenas o email e tipo de usuário
            FormEsqueciSenha2 formEsqueciSenha2 = new FormEsqueciSenha2(email, tipoUsuario);
            FormManager.EsqueciSenha(formEsqueciSenha2);

        } catch (RuntimeException ex) {
             MessagesAlert esqueciSenha = new MessagesAlert();
             esqueciSenha.showErrorMessage("Erro ao gerar token: "+ ex.getMessage());
        }
    }                                        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btEntrar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pDireita;
    private javax.swing.JPanel pEsquerda;
    private javax.swing.JPanel pLogin;
    private javax.swing.JTextField tfLogin;
    // End of variables declaration//GEN-END:variables
}
