package Visao.Telas;

import Persistencia.modelTemp.EnderecoModelCepApi;
import Persistencia.Entity.Endereco;
import Regradenegocio.EnderecoRN;
import Regradenegocio.PacienteRN;
import Services.ViaCepService;
import VO.EnderecoVO;
import VO.PacienteVO;
import Visao.Components.SimpleForm;
import Visao.Utils.RedimencionarIcones;
import Visao.Utils.EditorTextPaneEstilization;
import Visao.Utils.MessagesAlert;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.HeadlessException;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import raven.toast.Notifications;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author john
 */
public class FormValidarRelatos extends SimpleForm {


    /**
     * Creates new form telaCadastroPacientePanel
     */
    public FormValidarRelatos() {
        initComponents();
        //redimensionarIcones();

        RedimencionarIcones redimencionarIcone = new RedimencionarIcones();
        redimencionarIcone.redimensionarIcones(btSalvar, "/Multimidia/imagens/approved-icon.png", 40);
        redimencionarIcone.redimensionarIcones(btEditar, "/Multimidia/imagens/cancelar-btn.png", 40);
          pCentro.putClientProperty(FlatClientProperties.STYLE, "background:null");
          pIdentificacao.putClientProperty(FlatClientProperties.STYLE, "background:null");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbProntuario = new javax.swing.JLabel();
        lbLogoValidar = new javax.swing.JLabel();
        pCentro = new javax.swing.JPanel();
        pIdentificacao = new javax.swing.JPanel();
        lbEstagiario = new javax.swing.JLabel();
        lbPaciente = new javax.swing.JLabel();
        lbDataDoAtendimento = new javax.swing.JLabel();
        tfDataAtendimento = new javax.swing.JTextField();
        cbEstagiario = new javax.swing.JComboBox<>();
        cbSelecionarPaciente = new javax.swing.JComboBox<>();
        pBotoes = new javax.swing.JPanel();
        lbTextoRelato = new javax.swing.JLabel();
        lbPeriodoTrabalho = new javax.swing.JLabel();
        tfFeedback = new javax.swing.JTextField();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpTextoDoRelatorio = new javax.swing.JTextPane();

        dateChooser1.setTextField(tfDataAtendimento);
        dateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        setMaximumSize(new java.awt.Dimension(950, 835));
        setMinimumSize(new java.awt.Dimension(950, 835));
        setPreferredSize(new java.awt.Dimension(950, 835));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setMaximumSize(new java.awt.Dimension(950, 195));
        pNorth.setMinimumSize(new java.awt.Dimension(950, 195));
        pNorth.setPreferredSize(new java.awt.Dimension(950, 195));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbProntuario.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbProntuario.setForeground(new java.awt.Color(255, 255, 255));
        lbProntuario.setText("Validar Relatos ou Relatórios");

        lbLogoValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/imgRelatosRelatorios.png"))); // NOI18N

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogoValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbProntuario))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lbProntuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbClinica))
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLogoValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCentro.setBackground(java.awt.SystemColor.controlHighlight);
        pCentro.setAutoscrolls(true);
        pCentro.setPreferredSize(new java.awt.Dimension(950, 630));

        pIdentificacao.setBackground(java.awt.SystemColor.controlHighlight);
        pIdentificacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, btSalvar.getFont(), java.awt.SystemColor.controlDkShadow));
        pIdentificacao.setForeground(java.awt.SystemColor.controlHighlight);
        pIdentificacao.setMaximumSize(new java.awt.Dimension(950, 630));
        pIdentificacao.setMinimumSize(new java.awt.Dimension(950, 630));
        pIdentificacao.setPreferredSize(new java.awt.Dimension(950, 630));

        lbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstagiario.setForeground(new java.awt.Color(0, 102, 102));
        lbEstagiario.setText("Estagiário:");

        lbPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPaciente.setForeground(new java.awt.Color(0, 102, 102));
        lbPaciente.setText("Paciente:");

        lbDataDoAtendimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDataDoAtendimento.setForeground(new java.awt.Color(0, 102, 102));
        lbDataDoAtendimento.setText("Data do Atendimento:");

        tfDataAtendimento.setMaximumSize(new java.awt.Dimension(112, 36));
        tfDataAtendimento.setMinimumSize(new java.awt.Dimension(112, 36));
        tfDataAtendimento.setPreferredSize(new java.awt.Dimension(112, 36));

        cbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbEstagiario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bruna", "Pedro", "Maria" }));
        cbEstagiario.setMaximumSize(new java.awt.Dimension(112, 36));
        cbEstagiario.setMinimumSize(new java.awt.Dimension(112, 36));
        cbEstagiario.setPreferredSize(new java.awt.Dimension(112, 36));

        cbSelecionarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbSelecionarPaciente.setMaximumSize(new java.awt.Dimension(112, 36));
        cbSelecionarPaciente.setMinimumSize(new java.awt.Dimension(112, 36));
        cbSelecionarPaciente.setPreferredSize(new java.awt.Dimension(112, 36));

        javax.swing.GroupLayout pIdentificacaoLayout = new javax.swing.GroupLayout(pIdentificacao);
        pIdentificacao.setLayout(pIdentificacaoLayout);
        pIdentificacaoLayout.setHorizontalGroup(
            pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbEstagiario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbSelecionarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbDataDoAtendimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pIdentificacaoLayout.setVerticalGroup(
            pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstagiario)
                    .addComponent(cbEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSelecionarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataDoAtendimento)
                    .addComponent(tfDataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pBotoes.setBackground(java.awt.SystemColor.controlHighlight);
        pBotoes.setMaximumSize(new java.awt.Dimension(892, 30));
        pBotoes.setMinimumSize(new java.awt.Dimension(892, 30));
        pBotoes.setPreferredSize(new java.awt.Dimension(892, 30));

        javax.swing.GroupLayout pBotoesLayout = new javax.swing.GroupLayout(pBotoes);
        pBotoes.setLayout(pBotoesLayout);
        pBotoesLayout.setHorizontalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pBotoesLayout.setVerticalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        lbTextoRelato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbTextoRelato.setForeground(new java.awt.Color(0, 102, 102));
        lbTextoRelato.setText("Texto do Relatório:");

        lbPeriodoTrabalho.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPeriodoTrabalho.setForeground(new java.awt.Color(0, 102, 102));
        lbPeriodoTrabalho.setText("Feedback para o Aluno:");

        tfFeedback.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfFeedback.setToolTipText("ex. Rafael da Silva");

        btEditar.setBackground(new java.awt.Color(255, 51, 51));
        btEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btEditar.setForeground(new java.awt.Color(51, 51, 51));
        btEditar.setText("Solicitar Correções");

        btSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(51, 51, 51));
        btSalvar.setText("Aprovar");
        btSalvar.setMaximumSize(new java.awt.Dimension(227, 50));
        btSalvar.setMinimumSize(new java.awt.Dimension(227, 50));
        btSalvar.setPreferredSize(new java.awt.Dimension(227, 50));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tpTextoDoRelatorio);

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pIdentificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCentroLayout.createSequentialGroup()
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                            .addGroup(pCentroLayout.createSequentialGroup()
                                .addComponent(btEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfFeedback, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTextoRelato, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPeriodoTrabalho, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addComponent(pIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTextoRelato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPeriodoTrabalho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
    }//GEN-LAST:event_btSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbEstagiario;
    private javax.swing.JComboBox<String> cbSelecionarPaciente;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbDataDoAtendimento;
    private javax.swing.JLabel lbEstagiario;
    private javax.swing.JLabel lbLogoValidar;
    private javax.swing.JLabel lbPaciente;
    private javax.swing.JLabel lbPeriodoTrabalho;
    private javax.swing.JLabel lbProntuario;
    private javax.swing.JLabel lbTextoRelato;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pIdentificacao;
    private javax.swing.JPanel pNorth;
    private javax.swing.JTextField tfDataAtendimento;
    private javax.swing.JTextField tfFeedback;
    private javax.swing.JTextPane tpTextoDoRelatorio;
    // End of variables declaration//GEN-END:variables

}
