package Visao.Telas;

import OrientadorRN.OrientadorRN;
import Persistencia.Dao.CidadeDAO;
import Persistencia.Dao.EstadoDAO;
import Persistencia.Dao.PaisDAO;
import Persistencia.Entity.Cidade;
import Persistencia.modelTemp.EnderecoModelCepApi;
import Persistencia.Entity.Endereco;
import Persistencia.Entity.Estado;
import Persistencia.Entity.Pais;
import Regradenegocio.EnderecoRN;
import Regradenegocio.EstagiarioRN;
import Regradenegocio.PacienteRN;
import Services.ViaCepService;
import VO.EnderecoVO;
import VO.EstagiarioVO;
import VO.OrientadorVO;
import VO.PacienteVO;
import Visao.Components.SimpleForm;
import Visao.JframeManager.FormManager;
import Visao.Utils.RedimencionarIcones;
import Visao.Utils.EditorTextPaneEstilization;
import Visao.Utils.MessagesAlert;
import java.awt.HeadlessException;
import java.io.IOException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import raven.toast.Notifications;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author john
 */
public class FormTriagem extends SimpleForm {

    private Endereco enderecoObject;

    /**
     * Creates new form telaCadastroPacientePanel
     */
    public FormTriagem() {
        initComponents();
        //redimensionarIcones();

        EditorTextPaneEstilization.EstilizeEditorTextPane(tpDisponibilidade);
        
        inserirDadosFormulario();

        RedimencionarIcones redimencionarIcone = new RedimencionarIcones();
        redimencionarIcone.redimensionarIcones(btSalvar, "/Multimidia/imagens/salvar-btn.png");
        redimencionarIcone.redimensionarIcones(btEditar, "/Multimidia/imagens/editar-btn.png");
    }
    
    public void inserirDadosFormulario(){
        PaisDAO paisDaoInstancia = new PaisDAO();
        CidadeDAO cidadeDaoInstancia = new CidadeDAO();
        EstadoDAO estadoDaoInstancia = new EstadoDAO();
        OrientadorRN orientadorRn = new OrientadorRN();
        EstagiarioRN estagiarioRn = new EstagiarioRN();
        
        
        List<Pais> todosPaises = paisDaoInstancia.buscarTodos();
        List<Cidade> todasCidades = cidadeDaoInstancia.buscarTodos();
        List<Estado> todosEstados = estadoDaoInstancia.buscarTodos();
        
        List<OrientadorVO> todosOrientadores = orientadorRn.listarOrientadores();
        List<EstagiarioVO> todosEstagiarios = estagiarioRn.listarEstagiarios();
        
        cbNacionalidade.removeAllItems();
        cbEstado.removeAllItems();
        cbCidade.removeAllItems();
        
        cbEstagiario.removeAllItems();
        cbOrientador.removeAllItems();

        // Add Paises to Nacionalidade ComboBox
        for (Pais pais : todosPaises) {
            cbNacionalidade.addItem(String.valueOf(pais.getId()) + " - " + pais.getNome());  
        }

        // Add Estados to Estado ComboBox
        for (Estado estado : todosEstados) {
            cbEstado.addItem(String.valueOf(estado.getId()) + " - " +estado.getNome()); 
        }

        // Add Cidades to Cidade ComboBox
        for (Cidade cidade : todasCidades) {
            cbCidade.addItem(String.valueOf(cidade.getId()) + " - " + cidade.getNome());  
        }

        // Add Orientadores to Orientador ComboBox
        for (OrientadorVO orientador : todosOrientadores) {
            cbOrientador.addItem(String.valueOf(orientador.getId()) + " - " +orientador.getNomeCompleto());  
        }

        // Add Estagiarios to Estagiario ComboBox
        for (EstagiarioVO estagiario : todosEstagiarios) {
            cbEstagiario.addItem(String.valueOf(estagiario.getId()) + " - " + estagiario.getNomeCompleto());  
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbProntuario = new javax.swing.JLabel();
        pCentro = new javax.swing.JPanel();
        pIdentificacao = new javax.swing.JPanel();
        lbGenero = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        lbContato2 = new javax.swing.JLabel();
        ftfCelularContato = new javax.swing.JFormattedTextField();
        ftfCelular = new javax.swing.JFormattedTextField();
        lbCelular = new javax.swing.JLabel();
        tfPaciente = new javax.swing.JTextField();
        lbPaciente = new javax.swing.JLabel();
        lbDataNascimento = new javax.swing.JLabel();
        tfData = new javax.swing.JTextField();
        lbInstrucao = new javax.swing.JLabel();
        cbInstrucao = new javax.swing.JComboBox<>();
        lbProfissao = new javax.swing.JLabel();
        tfProfissao = new javax.swing.JTextField();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        lbEstadoCivil = new javax.swing.JLabel();
        cbRacaCorEtnia = new javax.swing.JComboBox<>();
        lbRaca = new javax.swing.JLabel();
        lbOrientacao = new javax.swing.JLabel();
        cbOrientacao = new javax.swing.JComboBox<>();
        lbContato3 = new javax.swing.JLabel();
        ftfCelularContato1 = new javax.swing.JFormattedTextField();
        pEndereco = new javax.swing.JPanel();
        lbCidade = new javax.swing.JLabel();
        lbRua = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        lbBairro = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        lbCep = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        tfComplemento = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        cbNacionalidade = new javax.swing.JComboBox<>();
        cbCidade = new javax.swing.JComboBox<>();
        btBuscarCep = new javax.swing.JButton();
        pBotoes = new javax.swing.JPanel();
        pInscricao = new javax.swing.JPanel();
        lbDisponibilidade = new javax.swing.JLabel();
        cbEstagiario = new javax.swing.JComboBox<>();
        lbEstagiario = new javax.swing.JLabel();
        lbResponsavel = new javax.swing.JLabel();
        cbOrientador = new javax.swing.JComboBox<>();
        lbOrientador = new javax.swing.JLabel();
        cbAtendido = new javax.swing.JCheckBox();
        lbAtendido = new javax.swing.JLabel();
        tfResponsavel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpDisponibilidade = new javax.swing.JTextPane();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        dateChooser1.setTextField(tfData);

        setMaximumSize(new java.awt.Dimension(1024, 1450));
        setMinimumSize(new java.awt.Dimension(1024, 1450));
        setPreferredSize(new java.awt.Dimension(1024, 1450));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setMaximumSize(new java.awt.Dimension(1024, 130));
        pNorth.setMinimumSize(new java.awt.Dimension(1024, 130));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbProntuario.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbProntuario.setForeground(new java.awt.Color(255, 255, 255));
        lbProntuario.setText("Cadastro de Paciente");

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbProntuario))
                .addGap(558, 558, 558))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(lbProntuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbClinica)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.PAGE_START);

        pCentro.setBackground(java.awt.SystemColor.controlHighlight);
        pCentro.setAutoscrolls(true);
        pCentro.setPreferredSize(new java.awt.Dimension(1024, 768));

        pIdentificacao.setBackground(java.awt.SystemColor.controlHighlight);
        pIdentificacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, btSalvar.getFont(), java.awt.SystemColor.controlDkShadow));
        pIdentificacao.setForeground(java.awt.SystemColor.controlHighlight);
        pIdentificacao.setMaximumSize(new java.awt.Dimension(1024, 450));
        pIdentificacao.setMinimumSize(new java.awt.Dimension(1024, 450));

        lbGenero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbGenero.setForeground(new java.awt.Color(0, 102, 102));
        lbGenero.setText("*Gênero:");

        cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não-Binário", "Outro", "Prefiro não informar" }));

        lbContato2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbContato2.setForeground(new java.awt.Color(0, 102, 102));
        lbContato2.setText("Celular (Recado):");

        try {
            ftfCelularContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCelularContato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        try {
            ftfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCelular.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbCelular.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCelular.setForeground(new java.awt.Color(0, 102, 102));
        lbCelular.setText("*Celular:");

        tfPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfPaciente.setToolTipText("ex. Rafael da Silva");

        lbPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPaciente.setForeground(new java.awt.Color(0, 102, 102));
        lbPaciente.setText("*Paciente:");

        lbDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDataNascimento.setForeground(new java.awt.Color(0, 102, 102));
        lbDataNascimento.setText("*Data de Nascimento:");

        tfData.setFont(tfPaciente.getFont());

        lbInstrucao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbInstrucao.setForeground(new java.awt.Color(0, 102, 102));
        lbInstrucao.setText("Grau de Instrução:");

        cbInstrucao.setFont(cbGenero.getFont());
        cbInstrucao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analfabeto", "Ensino Fundamental incompleto", "Ensino Fundamental completo", "Ensino Médio incompleto", "Ensino Médio completo", "Ensino Técnico", "Superior incompleto", "Superior completo", "Pós-graduação", "Mestrado", "Doutorado", "Pós-doutorado" }));

        lbProfissao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbProfissao.setForeground(new java.awt.Color(0, 102, 102));
        lbProfissao.setText("Profissão:");

        tfProfissao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfProfissao.setToolTipText("ex. Rafael da Silva");

        cbEstadoCivil.setFont(cbGenero.getFont());
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "União Estável", "Separado(a)" }));

        lbEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstadoCivil.setForeground(new java.awt.Color(0, 102, 102));
        lbEstadoCivil.setText("Estado Civil:");

        cbRacaCorEtnia.setFont(cbGenero.getFont());
        cbRacaCorEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negra", "Branca", "Amarela", "Parda", "Indígena" }));

        lbRaca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbRaca.setForeground(new java.awt.Color(0, 102, 102));
        lbRaca.setText("Raça/Cor/Etnia:");

        lbOrientacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbOrientacao.setForeground(new java.awt.Color(0, 102, 102));
        lbOrientacao.setText("Orientação Sexual:");

        cbOrientacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbOrientacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heterossexual", "Homossexual", "Bissexual", "Assexual", "Pansexual", "Demissexual", "Queer", "Omnissexual" }));

        lbContato3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbContato3.setForeground(new java.awt.Color(0, 102, 102));
        lbContato3.setText("Telefone (Responsável):");

        try {
            ftfCelularContato1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCelularContato1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout pIdentificacaoLayout = new javax.swing.GroupLayout(pIdentificacao);
        pIdentificacao.setLayout(pIdentificacaoLayout);
        pIdentificacaoLayout.setHorizontalGroup(
            pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbOrientacao)
                            .addComponent(cbOrientacao, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbProfissao))
                        .addGap(18, 18, 18)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbInstrucao)
                            .addComponent(cbInstrucao, 0, 385, Short.MAX_VALUE)))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstadoCivil))
                        .addGap(18, 18, 18)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRaca)
                            .addComponent(cbRacaCorEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(lbCelular, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDataNascimento, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbContato2)
                                    .addComponent(ftfCelularContato, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbGenero)
                            .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbContato3)
                            .addComponent(ftfCelularContato1))))
                .addContainerGap(851, Short.MAX_VALUE))
        );
        pIdentificacaoLayout.setVerticalGroup(
            pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascimento)
                    .addComponent(lbPaciente)
                    .addComponent(lbGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbContato3)
                            .addComponent(lbContato2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfCelularContato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfCelularContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbProfissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbInstrucao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbOrientacao)
                        .addGap(12, 12, 12)
                        .addComponent(cbOrientacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbEstadoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbRaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRacaCorEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pEndereco.setBackground(java.awt.SystemColor.controlHighlight);
        pEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, cbEstagiario.getFont(), java.awt.SystemColor.controlDkShadow));
        pEndereco.setPreferredSize(new java.awt.Dimension(908, 500));

        lbCidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCidade.setForeground(new java.awt.Color(0, 102, 102));
        lbCidade.setText("*Cidade:");

        lbRua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbRua.setForeground(new java.awt.Color(0, 102, 102));
        lbRua.setText("*Rua:");

        tfRua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfRua.setToolTipText("ex. Marechal Rondon");

        tfBairro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfBairro.setToolTipText("ex. Centro");

        lbBairro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbBairro.setForeground(new java.awt.Color(0, 102, 102));
        lbBairro.setText("*Bairro:");

        lbNumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(0, 102, 102));
        lbNumero.setText("*Número:");

        tfNumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNumeroKeyTyped(evt);
            }
        });

        cbEstado.setFont(cbGenero.getFont());
        cbEstado.setMaximumSize(new java.awt.Dimension(128, 39));
        cbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEstadoItemStateChanged(evt);
            }
        });

        lbCep.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCep.setForeground(new java.awt.Color(0, 102, 102));
        lbCep.setText("*CEP:");

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCep.setFont(ftfCelular.getFont());

        tfComplemento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfComplemento.setToolTipText("ex. Centro");

        lbComplemento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbComplemento.setForeground(new java.awt.Color(0, 102, 102));
        lbComplemento.setText("Complemento:");

        lbEstado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(0, 102, 102));
        lbEstado.setText("*Estado:");

        cbNacionalidade.setFont(cbGenero.getFont());
        cbNacionalidade.setMaximumSize(new java.awt.Dimension(128, 39));

        cbCidade.setFont(ftfCelularContato.getFont());

        btBuscarCep.setBackground(java.awt.SystemColor.menu);
        btBuscarCep.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btBuscarCep.setForeground(new java.awt.Color(51, 51, 51));
        btBuscarCep.setText("Buscar");
        btBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEnderecoLayout = new javax.swing.GroupLayout(pEndereco);
        pEndereco.setLayout(pEnderecoLayout);
        pEnderecoLayout.setHorizontalGroup(
            pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEnderecoLayout.createSequentialGroup()
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(tfNumero))
                        .addGap(18, 18, 18)
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBairro)
                            .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbComplemento)
                            .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pEnderecoLayout.createSequentialGroup()
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCidade)
                            .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1200, Short.MAX_VALUE))
                    .addGroup(pEnderecoLayout.createSequentialGroup()
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbNacionalidade, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCep)
                                .addGroup(pEnderecoLayout.createSequentialGroup()
                                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btBuscarCep))))
                        .addGap(37, 37, 37)
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRua)
                            .addGroup(pEnderecoLayout.createSequentialGroup()
                                .addComponent(tfRua)
                                .addGap(845, 845, 845))))))
        );
        pEnderecoLayout.setVerticalGroup(
            pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnderecoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(cbNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEnderecoLayout.createSequentialGroup()
                        .addComponent(lbCep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btBuscarCep)
                                .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnderecoLayout.createSequentialGroup()
                        .addComponent(lbNumero)
                        .addGap(51, 51, 51))
                    .addGroup(pEnderecoLayout.createSequentialGroup()
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbComplemento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnderecoLayout.createSequentialGroup()
                                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addComponent(tfComplemento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnderecoLayout.createSequentialGroup()
                        .addComponent(lbEstado)
                        .addGap(8, 8, 8)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnderecoLayout.createSequentialGroup()
                        .addComponent(lbCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        pBotoes.setBackground(java.awt.SystemColor.controlHighlight);
        pBotoes.setMaximumSize(new java.awt.Dimension(892, 30));
        pBotoes.setMinimumSize(new java.awt.Dimension(892, 30));
        pBotoes.setPreferredSize(new java.awt.Dimension(892, 30));

        javax.swing.GroupLayout pBotoesLayout = new javax.swing.GroupLayout(pBotoes);
        pBotoes.setLayout(pBotoesLayout);
        pBotoesLayout.setHorizontalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
        );
        pBotoesLayout.setVerticalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        pInscricao.setBackground(java.awt.SystemColor.controlHighlight);
        pInscricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, cbEstagiario.getFont(), java.awt.SystemColor.controlDkShadow));

        lbDisponibilidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDisponibilidade.setForeground(new java.awt.Color(0, 102, 102));
        lbDisponibilidade.setText("Disponibilidade:");

        cbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbEstagiario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bruna", "Pedro", "Maria" }));

        lbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstagiario.setForeground(new java.awt.Color(0, 102, 102));
        lbEstagiario.setText("*Estagiário:");

        lbResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbResponsavel.setForeground(new java.awt.Color(0, 102, 102));
        lbResponsavel.setText("Responsável:");

        cbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbOrientador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fernanda Costa", "Bruna", "Pedro", "Maria" }));

        lbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbOrientador.setForeground(new java.awt.Color(0, 102, 102));
        lbOrientador.setText("*Orientador:");

        cbAtendido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbAtendido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAtendido.setForeground(new java.awt.Color(0, 102, 102));
        lbAtendido.setText("Atendido:");

        tfResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tpDisponibilidade.setFont(cbEstadoCivil.getFont());
        jScrollPane1.setViewportView(tpDisponibilidade);

        javax.swing.GroupLayout pInscricaoLayout = new javax.swing.GroupLayout(pInscricao);
        pInscricao.setLayout(pInscricaoLayout);
        pInscricaoLayout.setHorizontalGroup(
            pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInscricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDisponibilidade)
                    .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(pInscricaoLayout.createSequentialGroup()
                            .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbOrientador))
                            .addGap(18, 18, 18)
                            .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pInscricaoLayout.createSequentialGroup()
                                    .addComponent(lbEstagiario)
                                    .addGap(183, 183, 183)
                                    .addComponent(lbResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pInscricaoLayout.createSequentialGroup()
                                    .addComponent(cbEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(6, 6, 6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 528, Short.MAX_VALUE)
                .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAtendido))
                .addGap(185, 185, 185))
        );
        pInscricaoLayout.setVerticalGroup(
            pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInscricaoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbDisponibilidade)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pInscricaoLayout.createSequentialGroup()
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAtendido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbOrientador, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pInscricaoLayout.createSequentialGroup()
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pInscricaoLayout.createSequentialGroup()
                                .addComponent(lbEstagiario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(pInscricaoLayout.createSequentialGroup()
                                .addComponent(lbResponsavel)
                                .addGap(6, 6, 6)))
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGap(17, 17, 17))
        );

        btSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(51, 51, 51));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btEditar.setBackground(new java.awt.Color(255, 255, 51));
        btEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btEditar.setForeground(new java.awt.Color(51, 51, 51));
        btEditar.setText("Editar");

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 1790, Short.MAX_VALUE)
                    .addComponent(pIdentificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCentroLayout.createSequentialGroup()
                        .addComponent(pBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(898, 898, 898))
                    .addComponent(pInscricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCentroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditar)
                .addGap(18, 18, 18)
                .addComponent(btSalvar)
                .addGap(842, 842, 842))
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addComponent(pIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btEditar))
                .addGap(80, 80, 80)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(pCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumeroKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfNumeroKeyTyped

    private void btBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCepActionPerformed
        if (ftfCep.getText().equals("")) {
            ftfCep.requestFocus();
        } else {
            ViaCepService cep = new ViaCepService();
            try {
                // Remove a máscara do CEP
                String cepSemMascara = ftfCep.getText().replaceAll("[^0-9]", "");

                EnderecoModelCepApi enderecoObject = cep.getEndereco(cepSemMascara);

                if (enderecoObject == null) {
                    throw new IOException("O CEP não retornou um endereço válido.");
                }

                tfRua.setText(enderecoObject.getLogradouro());
                tfBairro.setText(enderecoObject.getBairro());
                tfComplemento.setText(enderecoObject.getComplemento());
                // Supondo que cbCidade seja um JComboBox<String> e você queira adicionar a cidade retornada
                cbCidade.addItem(enderecoObject.getLocalidade());

                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Cep encontrado com sucesso!");

            } catch (IOException ex) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Erro ao buscar o CEP: " + ex.getMessage());
                Logger.getLogger(FormTriagem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btBuscarCepActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        PacienteRN pacienteRN = new PacienteRN();
        EnderecoRN enderecoRN = new EnderecoRN();
        LocalDate dataAgora = LocalDate.now();
        MessagesAlert messagesAlert = new MessagesAlert();

        try {
            EnderecoVO enderecoVO = new EnderecoVO(
                    tfRua.getText(),
                    Integer.parseInt(tfNumero.getText()),
                    tfBairro.getText(),
                    Integer.parseInt(cbCidade.getSelectedItem().toString().split(" - ")[0]),
                    ftfCep.getText(),
                    tfComplemento.getText()
            );

            Endereco enderecoEntity = enderecoRN.salvarEndereco(enderecoVO);

            // salvar o endereço
            if (enderecoEntity != null) {
               // Extract ID values from ComboBoxes
                String genero = cbGenero.getSelectedItem().toString();
                String celularContato = ftfCelularContato.getText();
                String celular = ftfCelular.getText();
                String pacienteNome = tfPaciente.getText();
                String dataNascimento = tfData.getText();
                String instrucao = cbInstrucao.getSelectedItem().toString();
                String profissao = tfProfissao.getText();
                String estadoCivil = cbEstadoCivil.getSelectedItem().toString();
                String racaCorEtnia = cbRacaCorEtnia.getSelectedItem().toString();
                String orientacao = cbOrientacao.getSelectedItem().toString();
                String nacionalidade = cbNacionalidade.getSelectedItem().toString().split(" - ")[0]; 
                String disponibilidade = tpDisponibilidade.getText();
                String estagiario = cbEstagiario.getSelectedItem().toString().split(" - ")[0];  
                String orientador = cbOrientador.getSelectedItem().toString().split(" - ")[0];  
                String responsavel = tfResponsavel.getText();
                boolean atendido = cbAtendido.isSelected();

                PacienteVO pacienteVO = new PacienteVO(
                        genero,
                        celularContato,
                        celular,
                        pacienteNome,
                        dataNascimento,
                        dataAgora,
                        instrucao,
                        profissao,
                        estadoCivil,
                        racaCorEtnia,
                        orientacao,
                        Integer.parseInt(nacionalidade),
                        disponibilidade,
                        Integer.parseInt(estagiario),
                        Integer.parseInt(orientador),
                        enderecoEntity,
                        responsavel,
                        atendido,
                        true
                );

                // salvar o paciente
                if (pacienteRN.salvarPaciente(pacienteVO)) {
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Paciente salvo com sucesso!");
                    FormManager.showForm(new PageWelcome());
                } else {
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Erro ao salvar o paciente.");
                }
            } else {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER,
                    "Erro ao salvar o endereço.");
            }

        } catch (HeadlessException | NumberFormatException e) {
            messagesAlert.showErrorMessage("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void cbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEstadoItemStateChanged
        CidadeDAO cidadeDaoInstancia = new CidadeDAO();
        String selectedStateId = cbEstado.getSelectedItem().toString().split(" - ")[0];;
        
        if (selectedStateId != null) {
            // Filter cities based on the selected state
            List<Cidade> filteredCidades = cidadeDaoInstancia.buscarPorEstado(Integer.parseInt(selectedStateId));
            cbCidade.removeAllItems();
            
            for (Cidade cidade : filteredCidades) {
                cbCidade.addItem(cidade.getId() + " - " + cidade.getNome());
            }
        }
    }//GEN-LAST:event_cbEstadoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarCep;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cbAtendido;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JComboBox<String> cbEstagiario;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbInstrucao;
    private javax.swing.JComboBox<String> cbNacionalidade;
    private javax.swing.JComboBox<String> cbOrientacao;
    private javax.swing.JComboBox<String> cbOrientador;
    private javax.swing.JComboBox<String> cbRacaCorEtnia;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JFormattedTextField ftfCelular;
    private javax.swing.JFormattedTextField ftfCelularContato;
    private javax.swing.JFormattedTextField ftfCelularContato1;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAtendido;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbContato2;
    private javax.swing.JLabel lbContato3;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbDisponibilidade;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstadoCivil;
    private javax.swing.JLabel lbEstagiario;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbInstrucao;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbOrientacao;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JLabel lbPaciente;
    private javax.swing.JLabel lbProfissao;
    private javax.swing.JLabel lbProntuario;
    private javax.swing.JLabel lbRaca;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbRua;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pEndereco;
    private javax.swing.JPanel pIdentificacao;
    private javax.swing.JPanel pInscricao;
    private javax.swing.JPanel pNorth;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPaciente;
    private javax.swing.JTextField tfProfissao;
    private javax.swing.JTextField tfResponsavel;
    private javax.swing.JTextField tfRua;
    private javax.swing.JTextPane tpDisponibilidade;
    // End of variables declaration//GEN-END:variables

}
