/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;

import Persistencia.Dao.CidadeDAO;
import Persistencia.Dao.EstadoDAO;
import Persistencia.Dao.PaisDAO;
import Persistencia.Entity.Cidade;
import Persistencia.Entity.Estado;
import Persistencia.Entity.Paciente;
import Persistencia.Entity.Pais;
import Persistencia.Model.EnderecoModelCepApi;
import Regradenegocio.EstagiarioRN;
import Regradenegocio.OrientadorRN;
import Regradenegocio.PacienteRN;
import Regradenegocio.SessaoRN;
import Services.ViaCepService;
import VO.EnderecoVO;
import VO.EstagiarioVO;
import VO.OrientadorVO;
import VO.PacienteVO;
import VO.ResponsavelVO;
import VO.SessaoVO;
import Visao.Components.PanelTemplate;
import Visao.JframeManager.FormManager;
import Visao.Utils.MessagesAlert;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import raven.toast.Notifications;

/**
 *
 * @author john
 */
public class FormBuscaAvancadaPaciente extends PanelTemplate {

    /**
     * Creates new form FormBuscaAvancada
     */
    public FormBuscaAvancadaPaciente() {
        initComponents();
        inserirDadosFormulario();
        filtroUsuarioPesquisador();

        //setupCalendarPopup(tfData);
        //setupCalendarPopup(tfInscricao);
    }

    private void filtroUsuarioPesquisador() {
        SessaoVO sessaoVO = new SessaoRN().buscarUltimaSessao();
        if (sessaoVO.getTipo().equals("Pesquisador")) {
            tfPaciente.setEnabled(false);
        }
    }

//    private void setupCalendarPopup(JTextField textField) {
//        textField.setEditable(false); // Optional: makes it read-only
//
//        textField.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                showCalendarDialog(textField);
//            }
//        });
//    }
//
//    private void showCalendarDialog(JTextField targetField) {
//        Window parentWindow = SwingUtilities.getWindowAncestor(this);
//        JDialog dialog = new JDialog(parentWindow, "Escolher Data", Dialog.ModalityType.APPLICATION_MODAL);
//
//        com.toedter.calendar.JCalendar calendar = new com.toedter.calendar.JCalendar();
//
//        dialog.getContentPane().add(calendar);
//        dialog.pack();
//        dialog.setLocationRelativeTo(this);
//
//        calendar.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent e) {
//                if (e.getClickCount() == 2) { // Double-click to select
//                    java.util.Date selectedDate = calendar.getDate();
//                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
//                    targetField.setText(sdf.format(selectedDate));
//                    dialog.dispose();
//                }
//            }
//        });
//
//        dialog.setVisible(true);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dcInscricao = new com.raven.datechooser.DateChooser();
        dcNascimento = new com.raven.datechooser.DateChooser();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbProntuario = new javax.swing.JLabel();
        pSouth = new javax.swing.JPanel();
        pIdentificacao = new javax.swing.JPanel();
        lbGenero = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        tfPaciente = new javax.swing.JTextField();
        lbPaciente = new javax.swing.JLabel();
        lbDataNascimento = new javax.swing.JLabel();
        tfData = new javax.swing.JTextField();
        lbInstrucao = new javax.swing.JLabel();
        cbInstrucao = new javax.swing.JComboBox<>();
        lbProfissao = new javax.swing.JLabel();
        tfProfissao = new javax.swing.JTextField();
        cbEstadoCivil = new javax.swing.JComboBox<>();
        lbEstadoCivil = new javax.swing.JLabel();
        cbRacaCorEtnia = new javax.swing.JComboBox<>();
        lbRaca = new javax.swing.JLabel();
        lbOrientacao = new javax.swing.JLabel();
        cbOrientacao = new javax.swing.JComboBox<>();
        pEndereco = new javax.swing.JPanel();
        lbCidade = new javax.swing.JLabel();
        lbRua = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        lbBairro = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        lbNaturalidade1 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lbCep = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        tfComplemento = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        cbNacionalidade = new javax.swing.JComboBox<>();
        cbCidade = new javax.swing.JComboBox<>();
        lbNaturalidade = new javax.swing.JLabel();
        cbNaturalidade = new javax.swing.JComboBox<>();
        btBuscarCep = new javax.swing.JButton();
        tfNumero = new javax.swing.JTextField();
        pInscricao = new javax.swing.JPanel();
        lbResponsavel = new javax.swing.JLabel();
        cbAtendido = new javax.swing.JCheckBox();
        lbAtendido = new javax.swing.JLabel();
        tfResponsavel = new javax.swing.JTextField();
        lbAtivo = new javax.swing.JLabel();
        cbAtivo = new javax.swing.JCheckBox();
        lbDataNascimento1 = new javax.swing.JLabel();
        tfInscricao = new javax.swing.JTextField();
        lbEstagiario = new javax.swing.JLabel();
        cbEstagiario = new javax.swing.JComboBox<>();
        cbOrientador = new javax.swing.JComboBox<>();
        lbOrientador = new javax.swing.JLabel();
        pBotoes = new javax.swing.JPanel();
        btLimparFiltros = new javax.swing.JButton();
        btAplicarFiltros = new javax.swing.JButton();

        dcInscricao.setTextField(tfInscricao);
        tfInscricao.setText("");

        dcNascimento.setTextField(tfData);
        tfData.setText("");

        setMaximumSize(new java.awt.Dimension(1000, 1350));
        setMinimumSize(new java.awt.Dimension(1000, 1350));
        setPreferredSize(new java.awt.Dimension(1000, 1350));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setMaximumSize(new java.awt.Dimension(1024, 130));
        pNorth.setMinimumSize(new java.awt.Dimension(1024, 130));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbProntuario.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbProntuario.setForeground(new java.awt.Color(255, 255, 255));
        lbProntuario.setText("Busca Avançada");

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbProntuario))
                .addGap(558, 558, 558))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(lbProntuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbClinica)
                .addGap(0, 71, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.NORTH);

        pSouth.setLayout(new javax.swing.BoxLayout(pSouth, javax.swing.BoxLayout.Y_AXIS));

        pIdentificacao.setBackground(java.awt.SystemColor.controlHighlight);
        pIdentificacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 13), java.awt.SystemColor.controlDkShadow)); // NOI18N
        pIdentificacao.setForeground(java.awt.SystemColor.controlHighlight);
        pIdentificacao.setMaximumSize(new java.awt.Dimension(980, 400));
        pIdentificacao.setMinimumSize(new java.awt.Dimension(980, 400));
        pIdentificacao.setPreferredSize(new java.awt.Dimension(980, 400));

        lbGenero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbGenero.setForeground(new java.awt.Color(0, 102, 102));
        lbGenero.setText("Gênero:");

        cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção", "Masculino", "Feminino", "Não-Binário", "Outro", "Prefiro não informar" }));

        tfPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfPaciente.setToolTipText("ex. Rafael da Silva");

        lbPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPaciente.setForeground(new java.awt.Color(0, 102, 102));
        lbPaciente.setText("Paciente:");

        lbDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDataNascimento.setForeground(new java.awt.Color(0, 102, 102));
        lbDataNascimento.setText("Data de Nascimento:");

        tfData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbInstrucao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbInstrucao.setForeground(new java.awt.Color(0, 102, 102));
        lbInstrucao.setText("Grau de Instrução:");

        cbInstrucao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbInstrucao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção", "Analfabeto", "Ensino Fundamental incompleto", "Ensino Fundamental completo", "Ensino Médio incompleto", "Ensino Médio completo", "Ensino Técnico", "Superior incompleto", "Superior completo", "Pós-graduação", "Mestrado", "Doutorado", "Pós-doutorado" }));

        lbProfissao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbProfissao.setForeground(new java.awt.Color(0, 102, 102));
        lbProfissao.setText("Profissão:");

        tfProfissao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfProfissao.setToolTipText("ex. Rafael da Silva");

        cbEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção", "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "União Estável", "Separado(a)" }));

        lbEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstadoCivil.setForeground(new java.awt.Color(0, 102, 102));
        lbEstadoCivil.setText("Estado Civil:");

        cbRacaCorEtnia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbRacaCorEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção", "Negro(a)", "Branco(a)", "Amarelo(a)", "Pardo(a)", "Indígena" }));

        lbRaca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbRaca.setForeground(new java.awt.Color(0, 102, 102));
        lbRaca.setText("Raça/Cor/Etnia:");

        lbOrientacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbOrientacao.setForeground(new java.awt.Color(0, 102, 102));
        lbOrientacao.setText("Orientação Sexual:");

        cbOrientacao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbOrientacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção", "Heterossexual", "Homossexual", "Bissexual", "Assexual", "Pansexual", "Demissexual", "Queer", "Omnissexual" }));

        javax.swing.GroupLayout pIdentificacaoLayout = new javax.swing.GroupLayout(pIdentificacao);
        pIdentificacao.setLayout(pIdentificacaoLayout);
        pIdentificacaoLayout.setHorizontalGroup(
            pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPaciente)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(tfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDataNascimento, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbGenero)
                            .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbOrientacao)
                            .addComponent(cbOrientacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEstadoCivil)
                            .addComponent(cbEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRaca)
                            .addComponent(cbRacaCorEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbProfissao))
                                .addGap(18, 18, 18)
                                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbInstrucao)
                                    .addComponent(cbInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pIdentificacaoLayout.setVerticalGroup(
            pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pIdentificacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNascimento)
                    .addComponent(lbPaciente)
                    .addComponent(lbGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbInstrucao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOrientacao)
                            .addComponent(lbProfissao))
                        .addGap(12, 12, 12)
                        .addComponent(cbOrientacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(pIdentificacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbEstadoCivil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pIdentificacaoLayout.createSequentialGroup()
                        .addComponent(lbRaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRacaCorEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pSouth.add(pIdentificacao);

        pEndereco.setBackground(java.awt.SystemColor.controlHighlight);
        pEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 13), java.awt.SystemColor.controlDkShadow)); // NOI18N
        pEndereco.setMaximumSize(new java.awt.Dimension(980, 450));
        pEndereco.setMinimumSize(new java.awt.Dimension(980, 450));

        lbCidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCidade.setForeground(new java.awt.Color(0, 102, 102));
        lbCidade.setText("Cidade:");

        lbRua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbRua.setForeground(new java.awt.Color(0, 102, 102));
        lbRua.setText("Rua:");

        tfRua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfRua.setToolTipText("ex. Marechal Rondon");

        tfBairro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfBairro.setToolTipText("ex. Centro");

        lbBairro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbBairro.setForeground(new java.awt.Color(0, 102, 102));
        lbBairro.setText("Bairro:");

        lbNumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(0, 102, 102));
        lbNumero.setText("Número:");

        lbNaturalidade1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNaturalidade1.setForeground(new java.awt.Color(0, 102, 102));
        lbNaturalidade1.setText("Nacionalidade:");

        cbEstado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção" }));
        cbEstado.setMaximumSize(new java.awt.Dimension(128, 39));
        cbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEstadoItemStateChanged(evt);
            }
        });

        lbCep.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCep.setForeground(new java.awt.Color(0, 102, 102));
        lbCep.setText("CEP:");

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCep.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tfComplemento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfComplemento.setToolTipText("ex. Centro");

        lbComplemento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbComplemento.setForeground(new java.awt.Color(0, 102, 102));
        lbComplemento.setText("Complemento:");

        lbEstado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(0, 102, 102));
        lbEstado.setText("Estado:");

        cbNacionalidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbNacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção" }));
        cbNacionalidade.setMaximumSize(new java.awt.Dimension(128, 39));
        cbNacionalidade.setMinimumSize(new java.awt.Dimension(448, 39));
        cbNacionalidade.setPreferredSize(new java.awt.Dimension(448, 39));
        cbNacionalidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNacionalidadeItemStateChanged(evt);
            }
        });

        cbCidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção" }));

        lbNaturalidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNaturalidade.setForeground(new java.awt.Color(0, 102, 102));
        lbNaturalidade.setText("Naturalidade:");

        cbNaturalidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbNaturalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção", "Abadia de Goiás (GO)", "Abadia dos Dourados (MG)", "Abadiânia (GO)", "Abaeté (MG)", "Abaetetuba (PA)", "Abaiara (CE)", "Abaíra (BA)", "Abaré (BA)", "Abatiá (PR)", "Abdon Batista (SC)", "Abelardo Luz (SC)", "Abel Figueiredo (PA)", "Abre Campo (MG)", "Abreu e Lima (PE)", "Abreulândia (TO)", "Acaiaca (MG)", "Açailândia (MA)", "Acajutiba (BA)", "Acará (PA)", "Acarape (CE)", "Acaraú (CE)", "Acari (RN)", "Acauã (PI)", "Aceguá (RS)", "Acopiara (CE)", "Acorizal (MT)", "Acrelândia (AC)", "Acreúna (GO)", "Açucena (MG)", "Adamantina (SP)", "Adelândia (GO)", "Adolfo (SP)", "Adrianópolis (PR)", "Adustina (BA)", "Afogados da Ingazeira (PE)", "Afonso Bezerra (RN)", "Afonso Cláudio (ES)", "Afonso Cunha (MA)", "Afrânio (PE)", "Afuá (PA)", "Agrestina (PE)", "Agricolândia (PI)", "Agrolândia (SC)", "Agronômica (SC)", "Água Azul do Norte (PA)", "Água Boa (MG)", "Água Boa (MT)", "Água Branca (AL)", "Água Branca (PB)", "Água Branca (PI)", "Água Clara (MS)", "Água Comprida (MG)", "Água Doce (SC)", "Água Doce do Maranhão (MA)", "Água Doce do Norte (ES)", "Água Fria (BA)", "Água Fria de Goiás (GO)", "Aguaí (SP)", "Água Limpa (GO)", "Aguanil (MG)", "Água Nova (RN)", "Água Preta (PE)", "Água Santa (RS)", "Águas Belas (PE)", "Águas da Prata (SP)", "Águas de Chapecó (SC)", "Águas de Lindóia (SP)", "Águas de Santa Bárbara (SP)", "Águas de São Pedro (SP)", "Águas Formosas (MG)", "Águas Frias (SC)", "Águas Lindas de Goiás (GO)", "Águas Mornas (SC)", "Águas Vermelhas (MG)", "Agudo (RS)", "Agudos (SP)", "Agudos do Sul (PR)", "Águia Branca (ES)", "Aguiar (PB)", "Aguiarnópolis (TO)", "Aimorés (MG)", "Aiquara (BA)", "Aiuaba (CE)", "Aiuruoca (MG)", "Ajuricaba (RS)", "Alagoa (MG)", "Alagoa Grande (PB)", "Alagoa Nova (PB)", "Alagoinha (PB)", "Alagoinha (PE)", "Alagoinha do Piauí (PI)", "Alagoinhas (BA)", "Alambari (SP)", "Albertina (MG)", "Alcântara (MA)", "Alcântaras (CE)", "Alcantil (PB)", "Alcinópolis (MS)", "Alcobaça (BA)", "Aldeias Altas (MA)", "Alecrim (RS)", "Alegre (ES)", "Alegrete (RS)", "Alegrete do Piauí (PI)", "Alegria (RS)", "Além Paraíba (MG)", "Alenquer (PA)", "Alexandria (RN)", "Alexânia (GO)", "Alfenas (MG)", "Alfredo Chaves (ES)", "Alfredo Marcondes (SP)", "Alfredo Vasconcelos (MG)", "Alfredo Wagner (SC)", "Algodão de Jandaíra (PB)", "Alhandra (PB)", "Aliança (PE)", "Aliança do Tocantins (TO)", "Almadina (BA)", "Almas (TO)", "Almeirim (PA)", "Almenara (MG)", "Almino Afonso (RN)", "Almirante Tamandaré (PR)", "Almirante Tamandaré do Sul (RS)", "Aloândia (GO)", "Alpercata (MG)", "Alpestre (RS)", "Alpinópolis (MG)", "Alta Floresta (MT)", "Alta Floresta d'Oeste (RO)", "Altair (SP)", "Altamira (PA)", "Altamira do Maranhão (MA)", "Altamira do Paraná (PR)", "Altaneira (CE)", "Alterosa (MG)", "Altinho (PE)", "Altinópolis (SP)", "Alto Alegre (RR)", "Alto Alegre (RS)", "Alto Alegre (SP)", "Alto Alegre do Maranhão (MA)", "Alto Alegre do Pindaré (MA)", "Alto Alegre dos Parecis (RO)", "Alto Araguaia (MT)", "Alto Bela Vista (SC)", "Alto da Boa Vista (MT)", "Alto Caparaó (MG)", "Alto do Rodrigues (RN)", "Alto Feliz (RS)", "Alto Garças (MT)", "Alto Horizonte (GO)", "Alto Jequitibá (MG)", "Alto Longá (PI)", "Altônia (PR)", "Alto Paraguai (MT)", "Alto Paraíso (PR)", "Alto Paraíso (RO)", "Alto Paraíso de Goiás (GO)", "Alto Paraná (PR)", "Alto Parnaíba (MA)", "Alto Piquiri (PR)", "Alto Rio Doce (MG)", "Alto Rio Novo (ES)", "Altos (PI)", "Alto Santo (CE)", "Alto Taquari (MT)", "Alumínio (SP)", "Alvarães (AM)", "Alvarenga (MG)", "Álvares Florence (SP)", "Álvares Machado (SP)", "Álvaro de Carvalho (SP)", "Alvinlândia (SP)", "Alvinópolis (MG)", "Alvorada (RS)", "Alvorada (TO)", "Alvorada de Minas (MG)", "Alvorada d'Oeste (RO)", "Alvorada do Gurgueia (PI)", "Alvorada do Norte (GO)", "Alvorada do Sul (PR)", "Amajari (RR)", "Amambai (MS)", "Amapá (AP)", "Amapá do Maranhão (MA)", "Amaporã (PR)", "Amaraji (PE)", "Amaral Ferrador (RS)", "Amaralina (GO)", "Amarante (PI)", "Amarante do Maranhão (MA)", "Amargosa (BA)", "Amaturá (AM)", "Amélia Rodrigues (BA)", "América Dourada (BA)", "Americana (SP)", "Americano do Brasil (GO)", "Américo Brasiliense (SP)", "Américo de Campos (SP)", "Ametista do Sul (RS)", "Amontada (CE)", "Amorinópolis (GO)", "Amparo (PB)", "Amparo (SP)", "Amparo do São Francisco (SE)", "Amparo do Serra (MG)", "Ampére (PR)", "Anadia (AL)", "Anagé (BA)", "Anahy (PR)", "Anajás (PA)", "Anajatuba (MA)", "Analândia (SP)", "Anamã (AM)", "Ananás (TO)", "Ananindeua (PA)", "Anápolis (GO)", "Anapu (PA)", "Anapurus (MA)", "Anastácio (MS)", "Anaurilândia (MS)", "Anchieta (ES)", "Anchieta (SC)", "Andaraí (BA)", "Andirá (PR)", "Andorinha (BA)", "Andradas (MG)", "Andradina (SP)", "André da Rocha (RS)", "Andrelândia (MG)", "Angatuba (SP)", "Angelândia (MG)", "Angélica (MS)", "Angelim (PE)", "Angelina (SC)", "Angical (BA)", "Angical do Piauí (PI)", "Angico (TO)", "Angicos (RN)", "Angra dos Reis (RJ)", "Anguera (BA)", "Ângulo (PR)", "Anhanguera (GO)", "Anhembi (SP)", "Anhumas (SP)", "Anicuns (GO)", "Anísio de Abreu (PI)", "Anita Garibaldi (SC)", "Anitápolis (SC)", "Anori (AM)", "Anta Gorda (RS)", "Antas (BA)", "Antonina (PR)", "Antonina do Norte (CE)", "Antônio Almeida (PI)", "Antônio Cardoso (BA)", "Antônio Carlos (MG)", "Antônio Carlos (SC)", "Antônio Dias (MG)", "Antônio Gonçalves (BA)", "Antônio João (MS)", "Antônio Martins (RN)", "Antônio Olinto (PR)", "Antônio Prado (RS)", "Antônio Prado de Minas (MG)", "Aparecida (PB)", "Aparecida (SP)", "Aparecida de Goiânia (GO)", "Aparecida d'Oeste (SP)", "Aparecida do Rio Doce (GO)", "Aparecida do Rio Negro (TO)", "Aparecida do Taboado (MS)", "Aperibé (RJ)", "Apiacá (ES)", "Apiacás (MT)", "Apiaí (SP)", "Apicum-Açu (MA)", "Apiúna (SC)", "Apodi (RN)", "Aporá (BA)", "Aporé (GO)", "Apuarema (BA)", "Apucarana (PR)", "Apuí (AM)", "Apuiarés (CE)", "Aquidabã (SE)", "Aquidauana (MS)", "Aquiraz (CE)", "Arabutã (SC)", "Araçagi (PB)", "Araçaí (MG)", "Aracaju (SE)", "Araçariguama (SP)", "Araçás (BA)", "Aracati (CE)", "Aracatu (BA)", "Araçatuba (SP)", "Araci (BA)", "Aracitaba (MG)", "Aracoiaba (CE)", "Araçoiaba (PE)", "Araçoiaba da Serra (SP)", "Aracruz (ES)", "Araçu (GO)", "Araçuaí (MG)", "Aragarças (GO)", "Aragoiânia (GO)", "Aragominas (TO)", "Araguacema (TO)", "Araguaçu (TO)", "Araguaiana (MT)", "Araguaína (TO)", "Araguainha (MT)", "Araguanã (MA)", "Araguanã (TO)", "Araguapaz (GO)", "Araguari (MG)", "Araguatins (TO)", "Araioses (MA)", "Aral Moreira (MS)", "Aramari (BA)", "Arambaré (RS)", "Arame (MA)", "Aramina (SP)", "Arandu (SP)", "Arantina (MG)", "Arapeí (SP)", "Arapiraca (AL)", "Arapoema (TO)", "Araponga (MG)", "Arapongas (PR)", "Araporã (MG)", "Arapoti (PR)", "Arapuá (MG)", "Arapuã (PR)", "Araputanga (MT)", "Araquari (SC)", "Arara (PB)", "Araranguá (SC)", "Araraquara (SP)", "Araras (SP)", "Ararendá (CE)", "Arari (MA)", "Araricá (RS)", "Araripe (CE)", "Araripina (PE)", "Araruama (RJ)", "Araruna (PB)", "Araruna (PR)", "Arataca (BA)", "Aratiba (RS)", "Aratuba (CE)", "Aratuípe (BA)", "Arauá (SE)", "Araucária (PR)", "Araújos (MG)", "Araxá (MG)", "Arceburgo (MG)", "Arco-Íris (SP)", "Arcos (MG)", "Arcoverde (PE)", "Areado (MG)", "Areal (RJ)", "Arealva (SP)", "Areia (PB)", "Areia Branca (RN)", "Areia Branca (SE)", "Areia de Baraúnas (PB)", "Areial (PB)", "Areias (SP)", "Areiópolis (SP)", "Arenápolis (MT)", "Arenópolis (GO)", "Arez (Rio Grande do Norte) (RN)", "Argirita (MG)", "Aricanduva (MG)", "Arinos (MG)", "Aripuanã (MT)", "Ariquemes (RO)", "Ariranha (SP)", "Ariranha do Ivaí (PR)", "Armação dos Búzios (RJ)", "Armazém (SC)", "Arneiroz (CE)", "Aroazes (PI)", "Aroeiras (PB)", "Aroeiras do Itaim (PI)", "Arraial (PI)", "Arraial do Cabo (RJ)", "Arraias (TO)", "Arroio do Meio (RS)", "Arroio do Padre (RS)", "Arroio do Sal (RS)", "Arroio dos Ratos (RS)", "Arroio do Tigre (RS)", "Arroio Grande (RS)", "Arroio Trinta (SC)", "Artur Nogueira (SP)", "Aruanã (GO)", "Arujá (SP)", "Arvoredo (SC)", "Arvorezinha (RS)", "Ascurra (SC)", "Aspásia (SP)", "Assaí (PR)", "Assaré (CE)", "Assis (SP)", "Assis Brasil (AC)", "Assis Chateaubriand (PR)", "Assu (RN)", "Assunção (PB)", "Assunção do Piauí (PI)", "Astolfo Dutra (MG)", "Astorga (PR)", "Atalaia (AL)", "Atalaia (PR)", "Atalaia do Norte (AM)", "Atalanta (SC)", "Ataléia (MG)", "Atibaia (SP)", "Atílio Vivácqua (ES)", "Augustinópolis (TO)", "Augusto Corrêa (PA)", "Augusto de Lima (MG)", "Augusto Pestana (RS)", "Áurea (RS)", "Aurelino Leal (BA)", "Auriflama (SP)", "Aurilândia (GO)", "Aurora (CE)", "Aurora (SC)", "Aurora do Pará (PA)", "Aurora do Tocantins (TO)", "Autazes (AM)", "Avaí (SP)", "Avanhandava (SP)", "Avaré (SP)", "Aveiro (PA)", "Avelino Lopes (PI)", "Avelinópolis (GO)", "Axixá (MA)", "Axixá do Tocantins (TO)" }));

        btBuscarCep.setBackground(java.awt.SystemColor.menu);
        btBuscarCep.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btBuscarCep.setForeground(new java.awt.Color(51, 51, 51));
        btBuscarCep.setText("Buscar");
        btBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCepActionPerformed(evt);
            }
        });

        tfNumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNumero.setToolTipText("ex. Marechal Rondon");

        javax.swing.GroupLayout pEnderecoLayout = new javax.swing.GroupLayout(pEndereco);
        pEndereco.setLayout(pEnderecoLayout);
        pEnderecoLayout.setHorizontalGroup(
            pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEnderecoLayout.createSequentialGroup()
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEnderecoLayout.createSequentialGroup()
                                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNumero))
                                .addGap(18, 18, 18)
                                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbBairro)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbComplemento)
                                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pEnderecoLayout.createSequentialGroup()
                                .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarCep, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbRua)))
                            .addGroup(pEnderecoLayout.createSequentialGroup()
                                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEstado)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCidade)
                                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbNaturalidade1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pEnderecoLayout.createSequentialGroup()
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNaturalidade)
                            .addComponent(cbNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
        );
        pEnderecoLayout.setVerticalGroup(
            pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNaturalidade1)
                    .addComponent(lbNaturalidade))
                .addGap(1, 1, 1)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCep)
                    .addComponent(lbRua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarCep, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumero)
                    .addComponent(lbBairro)
                    .addComponent(lbComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstado)
                    .addComponent(lbCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pSouth.add(pEndereco);

        pInscricao.setBackground(java.awt.SystemColor.controlHighlight);
        pInscricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 13), java.awt.SystemColor.controlDkShadow)); // NOI18N
        pInscricao.setMaximumSize(new java.awt.Dimension(980, 250));
        pInscricao.setMinimumSize(new java.awt.Dimension(980, 250));
        pInscricao.setPreferredSize(new java.awt.Dimension(980, 250));

        lbResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbResponsavel.setForeground(new java.awt.Color(0, 102, 102));
        lbResponsavel.setText("Responsável:");

        cbAtendido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbAtendido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAtendido.setForeground(new java.awt.Color(0, 102, 102));
        lbAtendido.setText("Atendido:");

        tfResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAtivo.setForeground(new java.awt.Color(0, 102, 102));
        lbAtivo.setText("Ativo:");

        cbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbDataNascimento1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDataNascimento1.setForeground(new java.awt.Color(0, 102, 102));
        lbDataNascimento1.setText("Data de Inscrição:");

        tfInscricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstagiario.setForeground(new java.awt.Color(0, 102, 102));
        lbEstagiario.setText("Estagiário:");

        cbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbEstagiario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção" }));

        cbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbOrientador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolher opção" }));

        lbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbOrientador.setForeground(new java.awt.Color(0, 102, 102));
        lbOrientador.setText("Orientador:");

        javax.swing.GroupLayout pInscricaoLayout = new javax.swing.GroupLayout(pInscricao);
        pInscricao.setLayout(pInscricaoLayout);
        pInscricaoLayout.setHorizontalGroup(
            pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInscricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInscricaoLayout.createSequentialGroup()
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOrientador))
                        .addGap(18, 18, 18)
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEstagiario)
                            .addComponent(cbEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAtivo)
                            .addComponent(cbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAtendido)
                            .addComponent(cbAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pInscricaoLayout.createSequentialGroup()
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDataNascimento1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        pInscricaoLayout.setVerticalGroup(
            pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInscricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInscricaoLayout.createSequentialGroup()
                        .addComponent(lbResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInscricaoLayout.createSequentialGroup()
                        .addComponent(lbDataNascimento1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfInscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pInscricaoLayout.createSequentialGroup()
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbOrientador)
                            .addComponent(lbEstagiario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(pInscricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pInscricaoLayout.createSequentialGroup()
                            .addComponent(lbAtendido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pInscricaoLayout.createSequentialGroup()
                            .addComponent(lbAtivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pSouth.add(pInscricao);

        pBotoes.setBackground(java.awt.SystemColor.controlHighlight);
        pBotoes.setMaximumSize(new java.awt.Dimension(980, 54));
        pBotoes.setMinimumSize(new java.awt.Dimension(980, 54));

        btLimparFiltros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btLimparFiltros.setForeground(new java.awt.Color(51, 51, 51));
        btLimparFiltros.setText("Limpar Filtros");
        btLimparFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparFiltrosActionPerformed(evt);
            }
        });

        btAplicarFiltros.setBackground(new java.awt.Color(102, 255, 102));
        btAplicarFiltros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAplicarFiltros.setForeground(new java.awt.Color(51, 51, 51));
        btAplicarFiltros.setText("Aplicar Filtros");
        btAplicarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAplicarFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotoesLayout = new javax.swing.GroupLayout(pBotoes);
        pBotoes.setLayout(pBotoesLayout);
        pBotoesLayout.setHorizontalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotoesLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(btLimparFiltros)
                .addGap(18, 18, 18)
                .addComponent(btAplicarFiltros)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        pBotoesLayout.setVerticalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparFiltros)
                    .addComponent(btAplicarFiltros))
                .addContainerGap())
        );

        pSouth.add(pBotoes);

        add(pSouth, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEstadoItemStateChanged
        CidadeDAO cidadeDaoInstancia = new CidadeDAO();
        Object selected = cbEstado.getSelectedItem();
        String estado = (selected != null && !selected.toString().equals("Escolher opção")) ? selected.toString() : null;

        if (estado != null) {
            // Extrai o número antes do " - "
            String idEstadoStr = estado.split(" - ")[0].trim();
            int idEstado = Integer.parseInt(idEstadoStr);

            List<Cidade> filteredCidades = cidadeDaoInstancia.buscarPorEstado(idEstado);
            cbCidade.removeAllItems();

            cbCidade.addItem("Escolher opção");
            for (Cidade cidade : filteredCidades) {
                cbCidade.addItem(cidade.getId() + " - " + cidade.getNome());
            }
        }
    }//GEN-LAST:event_cbEstadoItemStateChanged

    private void cbNacionalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNacionalidadeItemStateChanged
        String nacionalidadeSelecionada = String.valueOf(cbNacionalidade.getSelectedItem());

        if (!nacionalidadeSelecionada.contains("Brasil")) {
            // TODO
            // Colocar cidade estrangeira
        }
    }//GEN-LAST:event_cbNacionalidadeItemStateChanged

    private void btBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCepActionPerformed
        if (ftfCep.getText().equals("")) {
            ftfCep.requestFocus();
        } else {
            ViaCepService cep = new ViaCepService();
            try {
                // Remove a máscara do CEP
                String cepSemMascara = ftfCep.getText().replaceAll("[^0-9]", "");

                EnderecoModelCepApi enderecoObject = cep.getEndereco(cepSemMascara);

                if (enderecoObject == null) {
                    throw new IOException("O CEP não retornou um endereço válido.");
                }

                tfRua.setText(enderecoObject.getLogradouro());
                tfBairro.setText(enderecoObject.getBairro());
                tfComplemento.setText(enderecoObject.getComplemento());

                // Selecionar estado (uf)
                String uf = enderecoObject.getEstado();
                for (int i = 0; i < cbEstado.getItemCount(); i++) {
                    Object item = cbEstado.getItemAt(i);
                    if (item.toString().toLowerCase().contains(uf.toLowerCase())) {
                        cbEstado.setSelectedIndex(i);
                        break;
                    }
                }

                // Selecionar cidade
                String cidade = enderecoObject.getLocalidade();
                for (int i = 0; i < cbCidade.getItemCount(); i++) {
                    Object item = cbCidade.getItemAt(i);
                    if (item.toString().toLowerCase().contains(cidade.toLowerCase())) {
                        cbCidade.setSelectedIndex(i);
                        break;
                    }
                }

                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Cep encontrado com sucesso!");

            } catch (IOException ex) {
                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "Erro ao buscar o CEP: " + ex.getMessage());
                Logger.getLogger(FormPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btBuscarCepActionPerformed

    private void btLimparFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparFiltrosActionPerformed
        // TextFields
        tfPaciente.setText("");
        tfProfissao.setText("");
        tfResponsavel.setText("");
        tfRua.setText("");
        tfNumero.setText("");
        tfComplemento.setText("");
        tfBairro.setText("");
        tfData.setText("");
        tfInscricao.setText("");

        // FormattedTextField
        ftfCep.setText("");

        // ComboBoxes
        cbCidade.setSelectedIndex(0);
        cbEstado.setSelectedIndex(0);
        cbEstadoCivil.setSelectedIndex(0);
        cbEstagiario.setSelectedIndex(0);
        cbGenero.setSelectedIndex(0);
        cbInstrucao.setSelectedIndex(0);
        cbNacionalidade.setSelectedIndex(0);
        cbNaturalidade.setSelectedIndex(0);
        cbOrientacao.setSelectedIndex(0);
        cbOrientador.setSelectedIndex(0);
        cbRacaCorEtnia.setSelectedIndex(0);

        // Checkboxes
        cbAtendido.setSelected(false);
        cbAtivo.setSelected(false);

        // Limpar datas do dateChooser 
        //dcInscricao.setSelectedDate(new Date());
        tfData.setText("");
        tfInscricao.setText("");

    }//GEN-LAST:event_btLimparFiltrosActionPerformed

    private void btAplicarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAplicarFiltrosActionPerformed
        MessagesAlert messagesAlert = new MessagesAlert();
        try {
            String cep = ftfCep.getText().trim();

            // Remove caracteres não numéricos para checar se o campo está "vazio de verdade"
            cep = cep.replaceAll("[^\\d]", "");
            if (cep.isEmpty()) {
                cep = null;
            }

            // Número (com validação segura)
            Integer numero = null;
            String textoNumero = tfNumero.getText().trim();
            if (!textoNumero.isEmpty()) {
                try {
                    numero = Integer.valueOf(textoNumero);
                } catch (NumberFormatException e) {
                    messagesAlert.showErrorMessage("Número inválido no endereço.");
                    return;
                }
            }

            // Cidade (ID válido a partir da comboBox)
            Integer cidadeId = null;
            if (cbCidade.getSelectedIndex() > 0) {
                cidadeId = Integer.valueOf(cbCidade.getSelectedItem().toString().split(" - ")[0]);
            }

            // Criar VO do Endereço com dados limpos
            EnderecoVO enderecoVO = new EnderecoVO(
                    tfRua.getText().trim(),
                    numero,
                    tfBairro.getText().trim(),
                    cidadeId,
                    cep,
                    tfComplemento.getText().trim()
            );

            System.out.println("ENDERECOOOO" + enderecoVO.toString());

            // Criar VO de Responsável
            ResponsavelVO responsavelVO = new ResponsavelVO(
                    tfResponsavel.getText(),
                    null, null, null, null, null, null, null
            );

            // Criar VO de Paciente para Filtro
            PacienteVO filtro = new PacienteVO(
                    null, // id
                    tfPaciente.getText(), // nome
                    cbGenero.getSelectedItem().toString().equals("Escolher opção") ? null : cbGenero.getSelectedItem().toString(),
                    null, // celularContato
                    null, // celular
                    tfPaciente.getText(), // paciente
                    tfData.getText(), // dataNascimento
                    null, // dataInscricao
                    cbInstrucao.getSelectedItem().toString().equals("Escolher opção") ? null : cbInstrucao.getSelectedItem().toString(),
                    tfProfissao.getText(),
                    cbEstadoCivil.getSelectedItem().toString().equals("Escolher opção") ? null : cbEstadoCivil.getSelectedItem().toString(),
                    cbRacaCorEtnia.getSelectedItem().toString().equals("Escolher opção") ? null : cbRacaCorEtnia.getSelectedItem().toString(),
                    cbOrientacao.getSelectedItem().toString().equals("Escolher opção") ? null : cbOrientacao.getSelectedItem().toString(),
                    cbNacionalidade.getSelectedIndex() == 0 ? null : Integer.parseInt(cbNacionalidade.getSelectedItem().toString().split(" - ")[0]),
                    null, // disponibilidade
                    cbEstagiario.getSelectedIndex() == 0 ? null : Integer.parseInt(cbEstagiario.getSelectedItem().toString().split(" - ")[0]),
                    cbOrientador.getSelectedIndex() == 0 ? null : Integer.parseInt(cbOrientador.getSelectedItem().toString().split(" - ")[0]),
                    enderecoVO != null ? enderecoVO.toEntity() : null,
                    responsavelVO != null ? responsavelVO.toEntity() : null,
                    cbAtendido.isSelected(),
                    cbAtivo.isSelected(),
                    null // grupo
            );

            System.out.println("Visao.Telas.FormBuscaAvancadaPaciente.btAplicarFiltrosActionPerformed()");
            System.out.println(filtro.toString());

            // Buscar via RN
            PacienteRN pacienteRN = new PacienteRN();

            List<Paciente> pacientesFiltrados = pacienteRN.filtrarPacientes(filtro);

            System.out.println("Visao.Telas.FormBuscaAvancadaPaciente.btAplicarFiltrosActionPerformed()");
            System.out.println(Arrays.deepToString(pacientesFiltrados.toArray()));

            FormManager.showForm(new TableBuscaAvancadaPaciente(pacientesFiltrados, obterColunasDinamicas()));
        } catch (Exception e) {
            messagesAlert.showErrorMessage("Erro ao aplicar filtros: " + e.getMessage());
        }
    }//GEN-LAST:event_btAplicarFiltrosActionPerformed
    public List<String> obterColunasDinamicas() {
        List<String> colunasSelecionadas = new ArrayList<>();

        colunasSelecionadas.add("#");
        colunasSelecionadas.add("ID");

        if (!tfPaciente.getText().trim().isEmpty()) {
            colunasSelecionadas.add("Nome");
        }

        if (cbGenero.getSelectedIndex() > 0) {
            String genero = cbGenero.getSelectedItem().toString().trim();
            if (!genero.equalsIgnoreCase("null")) {
                colunasSelecionadas.add("Gênero");
            }
        }

        if (cbEstadoCivil.getSelectedIndex() > 0) {
            String ec = cbEstadoCivil.getSelectedItem().toString().trim();
            if (!ec.equalsIgnoreCase("null")) {
                colunasSelecionadas.add("Estado Civil");
            }
        }

        if (cbInstrucao.getSelectedIndex() > 0) {
            String instrucao = cbInstrucao.getSelectedItem().toString().trim();
            if (!instrucao.equalsIgnoreCase("null")) {
                colunasSelecionadas.add("Grau de Instrução");
            }
        }

        if (!tfProfissao.getText().trim().isEmpty()) {
            colunasSelecionadas.add("Profissão");
        }

        if (cbRacaCorEtnia.getSelectedIndex() > 0) {
            String raca = cbRacaCorEtnia.getSelectedItem().toString().trim();
            if (!raca.equalsIgnoreCase("null")) {
                colunasSelecionadas.add("Raça/Cor/Etnia");
            }
        }

        if (cbOrientacao.getSelectedIndex() > 0) {
            String orientacao = cbOrientacao.getSelectedItem().toString().trim();
            if (!orientacao.equalsIgnoreCase("null")) {
                colunasSelecionadas.add("Orientação Sexual");
            }
        }

        if (cbNacionalidade.getSelectedIndex() > 0) {
            colunasSelecionadas.add("Nacionalidade");
        }

        if (cbEstagiario.getSelectedIndex() > 0) {
            colunasSelecionadas.add("Estagiário");
        }

        if (cbOrientador.getSelectedIndex() > 0) {
            colunasSelecionadas.add("Orientador");
        }

        if (!tfData.getText().trim().isEmpty()) {
            colunasSelecionadas.add("Data de Nascimento");
        }

        if (cbAtivo.isSelected()) {
            colunasSelecionadas.add("Ativo");
        }

        if (cbAtendido.isSelected()) {
            colunasSelecionadas.add("Atendido");
        }

        String cep = ftfCep.getText().replaceAll("[^\\d]", "");
        if (!cep.isEmpty()) {
            colunasSelecionadas.add("CEP");
        }

        if (!tfRua.getText().trim().isEmpty()) {
            colunasSelecionadas.add("Endereço");
        }
        if (!tfNumero.getText().trim().isEmpty()) {
            colunasSelecionadas.add("Numero");
        }
        if (!tfBairro.getText().trim().isEmpty()) {
            colunasSelecionadas.add("Bairro");
        }
        if (!tfComplemento.getText().trim().isEmpty()) {
            colunasSelecionadas.add("Complemento");
        }

        if (cbCidade.getSelectedIndex() > 0) {
            colunasSelecionadas.add("Cidade");
        }
        if (cbEstado.getSelectedIndex() > 0) {
            colunasSelecionadas.add("Estado");
        }

        return colunasSelecionadas;
    }

    public void inserirDadosFormulario() {
        PaisDAO paisDaoInstancia = new PaisDAO();
        CidadeDAO cidadeDaoInstancia = new CidadeDAO();
        EstadoDAO estadoDaoInstancia = new EstadoDAO();
        OrientadorRN orientadorRn = new OrientadorRN();
        EstagiarioRN estagiarioRn = new EstagiarioRN();

        List<Pais> todosPaises = paisDaoInstancia.buscarTodos();
        List<Cidade> todasCidades = cidadeDaoInstancia.buscarTodos();
        List<Estado> todosEstados = estadoDaoInstancia.buscarTodos();

        List<OrientadorVO> todosOrientadores = orientadorRn.listarOrientadores();
        List<EstagiarioVO> todosEstagiarios = estagiarioRn.listarEstagiarios();

//        cbNacionalidade.removeAllItems();
//        cbEstado.removeAllItems();
//        cbCidade.removeAllItems();
//
//        cbEstagiario.removeAllItems();
//        cbOrientador.removeAllItems();
        // Add Paises to Nacionalidade ComboBox
        for (Pais pais : todosPaises) {
            cbNacionalidade.addItem(String.valueOf(pais.getId()) + " - " + pais.getNome());
        }

        // Add Estados to Estado ComboBox
        for (Estado estado : todosEstados) {
            cbEstado.addItem(String.valueOf(estado.getId()) + " - " + estado.getNome());
        }

        // Add Cidades to Cidade ComboBox
        for (Cidade cidade : todasCidades) {
            cbCidade.addItem(String.valueOf(cidade.getId()) + " - " + cidade.getNome());
        }

        // Add Orientadores to Orientador ComboBox
        for (OrientadorVO orientador : todosOrientadores) {
            cbOrientador.addItem(String.valueOf(orientador.getId()) + " - " + orientador.getNomeCompleto());
        }

        // Add Estagiarios to Estagiario ComboBox
        for (EstagiarioVO estagiario : todosEstagiarios) {
            cbEstagiario.addItem(String.valueOf(estagiario.getId()) + " - " + estagiario.getNomeCompleto());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAplicarFiltros;
    private javax.swing.JButton btBuscarCep;
    private javax.swing.JButton btLimparFiltros;
    private javax.swing.JCheckBox cbAtendido;
    private javax.swing.JCheckBox cbAtivo;
    private javax.swing.JComboBox<String> cbCidade;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbEstadoCivil;
    private javax.swing.JComboBox<String> cbEstagiario;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbInstrucao;
    private javax.swing.JComboBox<String> cbNacionalidade;
    private javax.swing.JComboBox<String> cbNaturalidade;
    private javax.swing.JComboBox<String> cbOrientacao;
    private javax.swing.JComboBox<String> cbOrientador;
    private javax.swing.JComboBox<String> cbRacaCorEtnia;
    private com.raven.datechooser.DateChooser dcInscricao;
    private com.raven.datechooser.DateChooser dcNascimento;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JLabel lbAtendido;
    private javax.swing.JLabel lbAtivo;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbDataNascimento1;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstadoCivil;
    private javax.swing.JLabel lbEstagiario;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbInstrucao;
    private javax.swing.JLabel lbNaturalidade;
    private javax.swing.JLabel lbNaturalidade1;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbOrientacao;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JLabel lbPaciente;
    private javax.swing.JLabel lbProfissao;
    private javax.swing.JLabel lbProntuario;
    private javax.swing.JLabel lbRaca;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbRua;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pEndereco;
    private javax.swing.JPanel pIdentificacao;
    private javax.swing.JPanel pInscricao;
    private javax.swing.JPanel pNorth;
    private javax.swing.JPanel pSouth;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfInscricao;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPaciente;
    private javax.swing.JTextField tfProfissao;
    private javax.swing.JTextField tfResponsavel;
    private javax.swing.JTextField tfRua;
    // End of variables declaration//GEN-END:variables
}
