/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;

import Persistencia.Dao.EstagiarioDAO;
import Persistencia.Entity.Estagiario;
import Regradenegocio.EstagiarioRN;
import Regradenegocio.OrientadorRN;
import VO.EstagiarioVO;
import VO.OrientadorVO;
import Visao.Components.PanelTemplate;
import Visao.Utils.MessagesAlert;
import Visao.Utils.RedimencionarIcones;
import com.formdev.flatlaf.FlatClientProperties;
import java.util.List;

/**
 *
 * @author john
 */
public class FormEstagiario extends PanelTemplate {

    private final MessagesAlert messagesAlert;

    /**
     * Creates new form estagiarioCadastro
     */
    public FormEstagiario() {
        initComponents();
        // remove background customizado e volta ao default do L&F
        pCentro.putClientProperty(FlatClientProperties.STYLE, "background:null");
        messagesAlert = new MessagesAlert();

        cbAtivo.setSelected(true);
        bloquearCampos(true);
        btSalvar.setEnabled(false);

        // redimensionarIcones();
        RedimencionarIcones redimencionarIcone = new RedimencionarIcones();
        redimencionarIcone.redimensionarIcones(btSalvar, "/Multimidia/imagens/approved-icon.png", 40);
        redimencionarIcone.redimensionarIcones(btEditar, "/Multimidia/imagens/editar-btn.png", 40);

        carregarEstagiarios();
        carregarOrientadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        bgSemestre = new javax.swing.ButtonGroup();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbProntuario = new javax.swing.JLabel();
        lbLogoEstagiario = new javax.swing.JLabel();
        pCentro = new javax.swing.JPanel();
        lbAtivo = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        lbOrientador = new javax.swing.JLabel();
        lbUsuarioEstagiario = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        cbAtivo = new javax.swing.JCheckBox();
        cbOrientador = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        cbEstagiario = new javax.swing.JComboBox<>();
        tfData = new javax.swing.JTextField();

        dateChooser1.setTextField(tfData);

        setMaximumSize(new java.awt.Dimension(800, 540));
        setMinimumSize(new java.awt.Dimension(800, 540));
        setPreferredSize(new java.awt.Dimension(800, 540));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setPreferredSize(new java.awt.Dimension(638, 189));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbProntuario.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbProntuario.setForeground(new java.awt.Color(255, 255, 255));
        lbProntuario.setText("Orientador x Estagiário  ");

        lbLogoEstagiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/logoVincularEstag.png"))); // NOI18N

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbLogoEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbProntuario))
                .addGap(0, 282, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbLogoEstagiario, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbProntuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbClinica)
                .addGap(57, 57, 57))
        );

        add(pNorth, java.awt.BorderLayout.NORTH);

        pCentro.setBackground(java.awt.SystemColor.controlHighlight);

        lbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAtivo.setForeground(new java.awt.Color(0, 102, 102));
        lbAtivo.setText("Ativo:");

        lbAno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAno.setForeground(new java.awt.Color(0, 102, 102));
        lbAno.setText("*Ano:");

        lbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbOrientador.setForeground(new java.awt.Color(0, 102, 102));
        lbOrientador.setText("*Orientador:");

        lbUsuarioEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbUsuarioEstagiario.setForeground(new java.awt.Color(0, 102, 102));
        lbUsuarioEstagiario.setText("*Estagiário:");

        btEditar.setBackground(new java.awt.Color(255, 255, 51));
        btEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btEditar.setForeground(new java.awt.Color(51, 51, 51));
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(51, 51, 51));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        cbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        cbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbOrientador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caroline", "João", "Marcelo" }));

        cbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbEstagiario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bruna", "Pedro", "Maria" }));

        tfData.setFont(cbOrientador.getFont());

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCentroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btEditar)
                .addGap(18, 18, 18)
                .addComponent(btSalvar)
                .addGap(29, 29, 29))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbEstagiario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbOrientador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbOrientador, 0, 420, Short.MAX_VALUE))
                    .addComponent(lbUsuarioEstagiario))
                .addGap(75, 75, 75)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAno)
                            .addComponent(tfData))
                        .addGap(47, 47, 47))
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAtivo)
                            .addComponent(cbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAno)
                    .addComponent(lbUsuarioEstagiario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addComponent(lbAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addComponent(lbOrientador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btSalvar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(pCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        bloquearCampos(false);
        btSalvar.setEnabled(true);
    }//GEN-LAST:event_btEditarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSalvarActionPerformed
        MessagesAlert messagesAlert = new MessagesAlert();
        String estagiarioSelecionado = (String) cbEstagiario.getSelectedItem();
        String orientadorSelecionado = (String) cbOrientador.getSelectedItem();
        String anoTextoCompleto = tfData.getText();
        boolean ativo = cbAtivo.isSelected();

        if (estagiarioSelecionado == null || orientadorSelecionado == null || anoTextoCompleto.isEmpty()) {
            messagesAlert.showErrorMessage("Todos os campos obrigatórios devem ser preenchidos.");
            return;
        }

        String anoTexto = anoTextoCompleto.substring(anoTextoCompleto.length() - 4);
        int ano;
        try {
            ano = Integer.parseInt(anoTexto);
        } catch (NumberFormatException e) {
            messagesAlert.showErrorMessage("O ano deve ser um número válido.");
            return;
        }

        EstagiarioRN estagiarioRN = new EstagiarioRN();
        EstagiarioVO estagiarioVO = estagiarioRN.buscarEstagiarioPorNome(estagiarioSelecionado);
        OrientadorVO orientadorVO = estagiarioRN.buscarOrientadorPorNome(orientadorSelecionado);

        if (estagiarioVO == null || orientadorVO == null) {
            messagesAlert.showErrorMessage("Estagiário ou Orientador não encontrado no banco.");
            return;
        }

        estagiarioVO.setAno(ano);
        estagiarioVO.setAtivo(ativo);
        estagiarioVO.setOrientadorVO(orientadorVO);

        boolean sucesso = estagiarioRN.atualizarEstagiario(estagiarioVO);

        if (sucesso) {
            if (!ativo) {
                desativarUsuarioCorrespondente(estagiarioVO);
            }
            messagesAlert.showSuccessMessage("Estagiário atualizado com sucesso!");
            bloquearCampos(true); // Bloqueia os campos após salvar
        } else {
            messagesAlert.showErrorMessage("Erro ao atualizar estagiário.");
        }
    }// GEN-LAST:event_btSalvarActionPerformed

    private void desativarUsuarioCorrespondente(EstagiarioVO estagiarioVO) {
        EstagiarioRN estagiarioRN = new EstagiarioRN();
        try {
            estagiarioRN.desativarEstagiario(estagiarioVO);
            messagesAlert.showSuccessMessage("Estagiário desativado com sucesso!");
        } catch (IllegalArgumentException e) {
            messagesAlert.showErrorMessage("Erro: " + e.getMessage());
        } catch (Exception e) {
            messagesAlert.showErrorMessage("Erro ao desativar estagiário: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSemestre;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cbAtivo;
    private javax.swing.JComboBox<String> cbEstagiario;
    private javax.swing.JComboBox<String> cbOrientador;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbAtivo;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbLogoEstagiario;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JLabel lbProntuario;
    private javax.swing.JLabel lbUsuarioEstagiario;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorth;
    private javax.swing.JTextField tfData;
    // End of variables declaration//GEN-END:variables

    private void carregarEstagiarios() {
        try {
            EstagiarioDAO estagiarioDAO = new EstagiarioDAO();
            List<Estagiario> estagiarios = estagiarioDAO.buscarTodos();

            cbEstagiario.removeAllItems();
            for (Estagiario estagiario : estagiarios) {
                cbEstagiario.addItem(estagiario.getNome());
            }
        } catch (Exception e) {
            messagesAlert.showErrorMessage("Não há estagiários cadastrados no sistema.");
            bloquearTodosOsCampos();
        }
    }

    // Método para carregar orientadores do banco
    private void carregarOrientadores() {
        try {
            OrientadorRN orientadorRN = new OrientadorRN();
            List<OrientadorVO> orientadores = orientadorRN.listar();

            cbOrientador.removeAllItems();
            for (OrientadorVO orientador : orientadores) {
                cbOrientador.addItem(orientador.getNomeCompleto());
            }
        } catch (Exception e) {
            messagesAlert.showErrorMessage("Erro ao carregar orientadores: " + e.getMessage());
        }
    }

    private void bloquearCampos(boolean bloquear) {
        cbEstagiario.setEnabled(!bloquear);
        cbOrientador.setEnabled(!bloquear);
        tfData.setEnabled(!bloquear);
        cbAtivo.setEnabled(!bloquear);
        btSalvar.setEnabled(!bloquear);
    }

    private void bloquearTodosOsCampos() {
        cbEstagiario.setEnabled(false);
        cbOrientador.setEnabled(false);
        tfData.setEnabled(false);
        cbAtivo.setEnabled(false);
        btEditar.setEnabled(false);
        btSalvar.setEnabled(false);
    }
}
