/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;
import java.awt.Image;
import javax.swing.ImageIcon;
import Visao.Components.SimpleForm;
import Visao.Utils.MessagesAlert;
import Visao.Utils.redimencionarIcones;

/**
 *
 * @author john
 */
public class MenuEstagiario extends SimpleForm {

    /**
     * Creates new form estagiarioMenu
     */
    public MenuEstagiario() {
        initComponents();
        //redimensionarIcones();
        
        redimencionarIcones redimencionarIcone = new redimencionarIcones();
        redimencionarIcone.redimensionarIcones(btGerenciarPacientes, "/Multimidia/imagens/cadastrar.png");
        redimencionarIcone.redimensionarIcones(btAcessarProntuario, "/Multimidia/imagens/prontuario.png");
        redimencionarIcone.redimensionarIcones(btAgendarConsulta, "/Multimidia/imagens/agendarConsulta.png");
        redimencionarIcone.redimensionarIcones(btProduzirRelato, "/Multimidia/imagens/editar-btn.png");
        redimencionarIcone.redimensionarIcones(btAcessarListaEspera, "/Multimidia/imagens/listaEspera.png");
        redimencionarIcone.redimensionarIcones(btDesconectar, "/Multimidia/imagens/desconectar.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pCentro = new javax.swing.JPanel();
        btGerenciarPacientes = new javax.swing.JButton();
        btAgendarConsulta = new javax.swing.JButton();
        btAcessarProntuario = new javax.swing.JButton();
        btProduzirRelato = new javax.swing.JButton();
        btAcessarListaEspera = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbOrientador = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(965, 607));
        setMinimumSize(new java.awt.Dimension(965, 607));
        setPreferredSize(new java.awt.Dimension(965, 607));
        setLayout(new java.awt.BorderLayout());

        pCentro.setBackground(java.awt.SystemColor.controlHighlight);
        pCentro.setLayout(new java.awt.GridBagLayout());

        btGerenciarPacientes.setBackground(new java.awt.Color(0, 114, 187));
        btGerenciarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btGerenciarPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btGerenciarPacientes.setText("Gerenciar Pacientes");
        btGerenciarPacientes.setMaximumSize(new java.awt.Dimension(300, 40));
        btGerenciarPacientes.setMinimumSize(new java.awt.Dimension(300, 40));
        btGerenciarPacientes.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btGerenciarPacientes, gridBagConstraints);

        btAgendarConsulta.setBackground(new java.awt.Color(140, 72, 67));
        btAgendarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAgendarConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btAgendarConsulta.setText("Agendar Consulta");
        btAgendarConsulta.setMaximumSize(new java.awt.Dimension(300, 40));
        btAgendarConsulta.setMinimumSize(new java.awt.Dimension(300, 40));
        btAgendarConsulta.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btAgendarConsulta, gridBagConstraints);

        btAcessarProntuario.setBackground(new java.awt.Color(86, 78, 88));
        btAcessarProntuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarProntuario.setForeground(new java.awt.Color(255, 255, 255));
        btAcessarProntuario.setText("Prontuário");
        btAcessarProntuario.setMaximumSize(new java.awt.Dimension(300, 40));
        btAcessarProntuario.setMinimumSize(new java.awt.Dimension(300, 40));
        btAcessarProntuario.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btAcessarProntuario, gridBagConstraints);

        btProduzirRelato.setBackground(new java.awt.Color(115, 87, 81));
        btProduzirRelato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btProduzirRelato.setForeground(new java.awt.Color(255, 255, 255));
        btProduzirRelato.setText("Produzir Relato");
        btProduzirRelato.setMaximumSize(new java.awt.Dimension(300, 40));
        btProduzirRelato.setMinimumSize(new java.awt.Dimension(300, 40));
        btProduzirRelato.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btProduzirRelato, gridBagConstraints);

        btAcessarListaEspera.setBackground(new java.awt.Color(51, 44, 35));
        btAcessarListaEspera.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarListaEspera.setForeground(new java.awt.Color(255, 255, 255));
        btAcessarListaEspera.setText("Lista de Espera");
        btAcessarListaEspera.setMaximumSize(new java.awt.Dimension(300, 40));
        btAcessarListaEspera.setMinimumSize(new java.awt.Dimension(300, 40));
        btAcessarListaEspera.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btAcessarListaEspera, gridBagConstraints);

        btDesconectar.setBackground(new java.awt.Color(255, 51, 51));
        btDesconectar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        btDesconectar.setText("Desconectar");
        btDesconectar.setMaximumSize(new java.awt.Dimension(300, 40));
        btDesconectar.setMinimumSize(new java.awt.Dimension(300, 40));
        btDesconectar.setPreferredSize(new java.awt.Dimension(300, 40));
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btDesconectar, gridBagConstraints);

        add(pCentro, java.awt.BorderLayout.CENTER);

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setPreferredSize(new java.awt.Dimension(638, 183));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbOrientador.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbOrientador.setForeground(new java.awt.Color(255, 255, 255));
        lbOrientador.setText("Estagiário");

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbOrientador))
                .addGap(0, 660, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(lbOrientador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbClinica)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        MessagesAlert logout = new MessagesAlert();
        logout.MessageAlertDesconectarOpcoes();
    }//GEN-LAST:event_btDesconectarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessarListaEspera;
    private javax.swing.JButton btAcessarProntuario;
    private javax.swing.JButton btAgendarConsulta;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JButton btGerenciarPacientes;
    private javax.swing.JButton btProduzirRelato;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorth;
    // End of variables declaration//GEN-END:variables
    
    private void redimensionarIcones(){
        
        //Gerenciar Pacientes
        ImageIcon iconeOriginalGerenciarPacientes = new ImageIcon(getClass().getResource("/imagens/cadastrar.png"));
        Image iconeEmEscalaGerenciarPacientes = iconeOriginalGerenciarPacientes.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btGerenciarPacientes.setIcon(new ImageIcon(iconeEmEscalaGerenciarPacientes));
        btGerenciarPacientes.setIconTextGap(10);
        
        //Acessar Prontuario
        ImageIcon iconeOriginalAcessarProntuario = new ImageIcon(getClass().getResource("/imagens/prontuario.png"));
        Image iconeEmEscalaAcessarProntuario = iconeOriginalAcessarProntuario.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btAcessarProntuario.setIcon(new ImageIcon(iconeEmEscalaAcessarProntuario));
        btAcessarProntuario.setIconTextGap(10);
        
        //Agendar Consulta
        ImageIcon iconeOriginalAgendarConsulta = new ImageIcon(getClass().getResource("/imagens/agendarConsulta.png"));
        Image iconeEmEscalaAgendarConsulta = iconeOriginalAgendarConsulta.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btAgendarConsulta.setIcon(new ImageIcon(iconeEmEscalaAgendarConsulta));
        btAgendarConsulta.setIconTextGap(10);
        
        //Produzir Relato
        ImageIcon iconeOriginalProduzirRelato = new ImageIcon(getClass().getResource("/imagens/editar-btn.png"));
        Image iconeEmEscalaProduzirRelato = iconeOriginalProduzirRelato.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btProduzirRelato.setIcon(new ImageIcon(iconeEmEscalaProduzirRelato));
        btProduzirRelato.setIconTextGap(10);

        //Acessar Lista de Espera
        ImageIcon iconeOriginalAcessarListaEspera = new ImageIcon(getClass().getResource("/imagens/listaEspera.png"));
        Image iconeEmEscalaAcessarListaEspera = iconeOriginalAcessarListaEspera.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btAcessarListaEspera.setIcon(new ImageIcon(iconeEmEscalaAcessarListaEspera));
        btAcessarListaEspera.setIconTextGap(10);
        
        //Desconectar
        ImageIcon iconeOriginalDesconectar = new ImageIcon(getClass().getResource("/imagens/desconectar.png"));
        Image iconeEmEscalaDesconectar = iconeOriginalDesconectar.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btDesconectar.setIcon(new ImageIcon(iconeEmEscalaDesconectar));
        btDesconectar.setIconTextGap(10);
    }

}
