/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;
import java.awt.Image;
import javax.swing.ImageIcon;
import Visao.Components.SimpleForm;
import Visao.Utils.MessagesAlert;
import Visao.Utils.redimencionarIcones;

/**
 *
 * @author john
 */
public class MenuAdministrador extends SimpleForm {

    /**
     * Creates new form administradorMenu
     */
    public MenuAdministrador() {
        initComponents();
        //redimensionarIcones();

        redimencionarIcones redimencionarIcone = new redimencionarIcones();
        redimencionarIcone.redimensionarIcones(btUsuario, "/Multimidia/imagens/usuario.png");
        redimencionarIcone.redimensionarIcones(btAcessarListaEspera, "/Multimidia/imagens/listaEspera.png");
        redimencionarIcone.redimensionarIcones(btCadastrarSecretaria, "/Multimidia/imagens/secretaria.png");
        redimencionarIcone.redimensionarIcones(btCadastrarUsuarios, "/Multimidia/imagens/cadastrar.png");
        redimencionarIcone.redimensionarIcones(btGerenciarAgenda, "/Multimidia/imagens/agenda.png");
        redimencionarIcone.redimensionarIcones(btGerenciarUsuarios, "/Multimidia/imagens/cadastrar.png");
        redimencionarIcone.redimensionarIcones(btGerenciarPermissoes, "/Multimidia/imagens/editar-btn.png");
        redimencionarIcone.redimensionarIcones(btDesconectar, "/Multimidia/imagens/desconectar.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbProntuario = new javax.swing.JLabel();
        pCentro = new javax.swing.JPanel();
        btCadastrarSecretaria = new javax.swing.JButton();
        btCadastrarUsuarios = new javax.swing.JButton();
        btGerenciarPermissoes = new javax.swing.JButton();
        btGerenciarAgenda = new javax.swing.JButton();
        btAcessarListaEspera = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        btGerenciarUsuarios = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(950, 630));
        setMinimumSize(new java.awt.Dimension(950, 630));
        setPreferredSize(new java.awt.Dimension(950, 630));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setPreferredSize(new java.awt.Dimension(638, 183));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbProntuario.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbProntuario.setForeground(new java.awt.Color(255, 255, 255));
        lbProntuario.setText("Administrador");

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbProntuario))
                .addContainerGap(738, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(0, 60, Short.MAX_VALUE)
                .addComponent(lbProntuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbClinica)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.NORTH);

        pCentro.setBackground(java.awt.SystemColor.controlHighlight);
        pCentro.setPreferredSize(new java.awt.Dimension(1024, 768));
        pCentro.setLayout(new java.awt.GridBagLayout());

        btCadastrarSecretaria.setBackground(new java.awt.Color(64, 61, 88));
        btCadastrarSecretaria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btCadastrarSecretaria.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarSecretaria.setText("Cadastrar Secretária");
        btCadastrarSecretaria.setMaximumSize(new java.awt.Dimension(150, 40));
        btCadastrarSecretaria.setMinimumSize(new java.awt.Dimension(150, 40));
        btCadastrarSecretaria.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 20, 6);
        pCentro.add(btCadastrarSecretaria, gridBagConstraints);

        btCadastrarUsuarios.setBackground(new java.awt.Color(91, 46, 72));
        btCadastrarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btCadastrarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarUsuarios.setText("Cadastrar Usuários");
        btCadastrarUsuarios.setMaximumSize(new java.awt.Dimension(150, 40));
        btCadastrarUsuarios.setMinimumSize(new java.awt.Dimension(150, 40));
        btCadastrarUsuarios.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 20, 6);
        pCentro.add(btCadastrarUsuarios, gridBagConstraints);

        btGerenciarPermissoes.setBackground(new java.awt.Color(30, 27, 24));
        btGerenciarPermissoes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btGerenciarPermissoes.setForeground(new java.awt.Color(255, 255, 255));
        btGerenciarPermissoes.setText("Permissões");
        btGerenciarPermissoes.setMaximumSize(new java.awt.Dimension(150, 40));
        btGerenciarPermissoes.setMinimumSize(new java.awt.Dimension(150, 40));
        btGerenciarPermissoes.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 20, 6);
        pCentro.add(btGerenciarPermissoes, gridBagConstraints);

        btGerenciarAgenda.setBackground(new java.awt.Color(34, 56, 67));
        btGerenciarAgenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btGerenciarAgenda.setForeground(new java.awt.Color(255, 255, 255));
        btGerenciarAgenda.setText("Gerenciar Agenda");
        btGerenciarAgenda.setMaximumSize(new java.awt.Dimension(150, 40));
        btGerenciarAgenda.setMinimumSize(new java.awt.Dimension(150, 40));
        btGerenciarAgenda.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 20, 6);
        pCentro.add(btGerenciarAgenda, gridBagConstraints);

        btAcessarListaEspera.setBackground(new java.awt.Color(28, 16, 24));
        btAcessarListaEspera.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarListaEspera.setForeground(new java.awt.Color(255, 255, 255));
        btAcessarListaEspera.setText("Lista de Espera");
        btAcessarListaEspera.setMaximumSize(new java.awt.Dimension(150, 40));
        btAcessarListaEspera.setMinimumSize(new java.awt.Dimension(150, 40));
        btAcessarListaEspera.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 20, 6);
        pCentro.add(btAcessarListaEspera, gridBagConstraints);

        btUsuario.setBackground(new java.awt.Color(9, 77, 146));
        btUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        btUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btUsuario.setText("Usuário");
        btUsuario.setMaximumSize(new java.awt.Dimension(150, 40));
        btUsuario.setMinimumSize(new java.awt.Dimension(150, 40));
        btUsuario.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 20, 6);
        pCentro.add(btUsuario, gridBagConstraints);

        btGerenciarUsuarios.setBackground(new java.awt.Color(88, 100, 29));
        btGerenciarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btGerenciarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btGerenciarUsuarios.setText("Gerenciar Usuários");
        btGerenciarUsuarios.setMaximumSize(new java.awt.Dimension(150, 40));
        btGerenciarUsuarios.setMinimumSize(new java.awt.Dimension(150, 40));
        btGerenciarUsuarios.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 170, 20, 6);
        pCentro.add(btGerenciarUsuarios, gridBagConstraints);

        btDesconectar.setBackground(new java.awt.Color(255, 51, 51));
        btDesconectar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        btDesconectar.setText("Desconectar");
        btDesconectar.setMaximumSize(new java.awt.Dimension(150, 40));
        btDesconectar.setMinimumSize(new java.awt.Dimension(150, 40));
        btDesconectar.setPreferredSize(new java.awt.Dimension(150, 40));
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 20, 150);
        pCentro.add(btDesconectar, gridBagConstraints);

        add(pCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        MessagesAlert logout = new MessagesAlert();
        logout.MessageAlertDesconectarOpcoes();
    }//GEN-LAST:event_btDesconectarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessarListaEspera;
    private javax.swing.JButton btCadastrarSecretaria;
    private javax.swing.JButton btCadastrarUsuarios;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JButton btGerenciarAgenda;
    private javax.swing.JButton btGerenciarPermissoes;
    private javax.swing.JButton btGerenciarUsuarios;
    private javax.swing.JButton btUsuario;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbProntuario;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorth;
    // End of variables declaration//GEN-END:variables
    
    private void redimensionarIcones(){
        
        //botao Usuario
        ImageIcon iconeOriginalUsuario = new ImageIcon(getClass().getResource("/imagens/usuario.png"));
        Image iconeEmEscalaUsuario = iconeOriginalUsuario.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btUsuario.setIcon(new ImageIcon(iconeEmEscalaUsuario));
        btUsuario.setIconTextGap(10);
        
        //botao lista de espera
        ImageIcon iconeOriginalListaDeEspera = new ImageIcon(getClass().getResource("/imagens/listaEspera.png"));
        Image iconeEmEscalaListaDeEspera = iconeOriginalListaDeEspera.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btAcessarListaEspera.setIcon(new ImageIcon(iconeEmEscalaListaDeEspera));
        btAcessarListaEspera.setIconTextGap(10);
        
        //CadastrarSecretaria
        ImageIcon iconeOriginalSecretaria = new ImageIcon(getClass().getResource("/imagens/secretaria.png"));
        Image iconeEmEscalaSecretaria = iconeOriginalSecretaria.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btCadastrarSecretaria.setIcon(new ImageIcon(iconeEmEscalaSecretaria));
        btCadastrarSecretaria.setIconTextGap(10);
        
        //Cadastrar Usuarios
        ImageIcon iconeOriginalCadastrarUsuarios = new ImageIcon(getClass().getResource("/imagens/cadastrar.png"));
        Image iconeEmEscalaCadastrarUsuarios = iconeOriginalCadastrarUsuarios.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btCadastrarUsuarios.setIcon(new ImageIcon(iconeEmEscalaCadastrarUsuarios));
        btCadastrarUsuarios.setIconTextGap(10);
        
        //Gerenciar Agenda
        ImageIcon iconeOriginalGerenciarAgenda = new ImageIcon(getClass().getResource("/imagens/agenda.png"));
        Image iconeEmEscalaGerenciarAgenda = iconeOriginalGerenciarAgenda.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btGerenciarAgenda.setIcon(new ImageIcon(iconeEmEscalaGerenciarAgenda));
        btGerenciarAgenda.setIconTextGap(10);

        //Gerenciar Usuarios
        ImageIcon iconeOriginalGerenciarUsuarios = new ImageIcon(getClass().getResource("/imagens/cadastrar.png"));
        Image iconeEmEscalaGerenciarUsuarios = iconeOriginalGerenciarUsuarios.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btGerenciarUsuarios.setIcon(new ImageIcon(iconeEmEscalaGerenciarUsuarios));
        btGerenciarUsuarios.setIconTextGap(10);

        //Gerenciar Permissoes
        ImageIcon iconeOriginalGerenciarPermissoes = new ImageIcon(getClass().getResource("/imagens/editar-btn.png"));
        Image iconeEmEscalaGerenciarPermissoes = iconeOriginalGerenciarPermissoes.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btGerenciarPermissoes.setIcon(new ImageIcon(iconeEmEscalaGerenciarPermissoes));
        btGerenciarPermissoes.setIconTextGap(10);

        //Desconectar
        ImageIcon iconeOriginalDesconectar = new ImageIcon(getClass().getResource("/imagens/desconectar.png"));
        Image iconeEmEscalaDesconectar = iconeOriginalDesconectar.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btDesconectar.setIcon(new ImageIcon(iconeEmEscalaDesconectar));
        btDesconectar.setIconTextGap(10);
    }

}
