/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;
import Visao.Components.SimpleForm;
import Visao.JframeManager.FormManager;
import Visao.Utils.MessagesAlert;
import Visao.Utils.RedimencionarIcones;

/**
 *
 * @author john
 */
public class MenuSecretaria extends SimpleForm {

    /**
     * Creates new form secretariaMenu
     */
    public MenuSecretaria() {
        initComponents();
        
        RedimencionarIcones redimencionarIcone = new RedimencionarIcones();
        redimencionarIcone.redimensionarIcones(btCadastrarPaciente, "/Multimidia/imagens/cadastrar.png");
        redimencionarIcone.redimensionarIcones(btCadastrarEstagiario, "/Multimidia/imagens/estagiario.png");
        redimencionarIcone.redimensionarIcones(btCadastrarOrientador, "/Multimidia/imagens/cadastrar.png");
        redimencionarIcone.redimensionarIcones(btVisualizarAgenda, "/Multimidia/imagens/agenda.png");
        redimencionarIcone.redimensionarIcones(btDesconectar, "/Multimidia/imagens/desconectar.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pCentro = new javax.swing.JPanel();
        btCadastrarPaciente = new javax.swing.JButton();
        btCadastrarEstagiario = new javax.swing.JButton();
        btCadastrarOrientador = new javax.swing.JButton();
        btVisualizarAgenda = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbOrientador = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(950, 630));
        setMinimumSize(new java.awt.Dimension(950, 630));
        setPreferredSize(new java.awt.Dimension(950, 630));
        setLayout(new java.awt.BorderLayout());

        pCentro.setBackground(java.awt.SystemColor.controlHighlight);
        pCentro.setPreferredSize(new java.awt.Dimension(700, 300));
        pCentro.setLayout(new java.awt.GridBagLayout());

        btCadastrarPaciente.setBackground(new java.awt.Color(41, 115, 115));
        btCadastrarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btCadastrarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarPaciente.setText("Cadastrar Paciente");
        btCadastrarPaciente.setMaximumSize(new java.awt.Dimension(300, 40));
        btCadastrarPaciente.setMinimumSize(new java.awt.Dimension(300, 40));
        btCadastrarPaciente.setPreferredSize(new java.awt.Dimension(300, 40));
        btCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 26, 6);
        pCentro.add(btCadastrarPaciente, gridBagConstraints);

        btCadastrarEstagiario.setBackground(new java.awt.Color(84, 68, 43));
        btCadastrarEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btCadastrarEstagiario.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarEstagiario.setText("Cadastrar Estagiário");
        btCadastrarEstagiario.setMaximumSize(new java.awt.Dimension(300, 40));
        btCadastrarEstagiario.setMinimumSize(new java.awt.Dimension(300, 40));
        btCadastrarEstagiario.setPreferredSize(new java.awt.Dimension(300, 40));
        btCadastrarEstagiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarEstagiarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 6, 20, 6);
        pCentro.add(btCadastrarEstagiario, gridBagConstraints);

        btCadastrarOrientador.setBackground(new java.awt.Color(192, 50, 33));
        btCadastrarOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btCadastrarOrientador.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarOrientador.setText("Cadastrar Orientador");
        btCadastrarOrientador.setMaximumSize(new java.awt.Dimension(300, 40));
        btCadastrarOrientador.setMinimumSize(new java.awt.Dimension(300, 40));
        btCadastrarOrientador.setPreferredSize(new java.awt.Dimension(300, 40));
        btCadastrarOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarOrientadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 26, 6);
        pCentro.add(btCadastrarOrientador, gridBagConstraints);

        btVisualizarAgenda.setBackground(new java.awt.Color(84, 94, 117));
        btVisualizarAgenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btVisualizarAgenda.setForeground(new java.awt.Color(255, 255, 255));
        btVisualizarAgenda.setText("Visualizar Agenda");
        btVisualizarAgenda.setMaximumSize(new java.awt.Dimension(300, 40));
        btVisualizarAgenda.setMinimumSize(new java.awt.Dimension(300, 40));
        btVisualizarAgenda.setPreferredSize(new java.awt.Dimension(300, 40));
        btVisualizarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarAgendaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(26, 6, 20, 6);
        pCentro.add(btVisualizarAgenda, gridBagConstraints);

        btDesconectar.setBackground(new java.awt.Color(255, 51, 51));
        btDesconectar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        btDesconectar.setText("Desconectar");
        btDesconectar.setMaximumSize(new java.awt.Dimension(300, 40));
        btDesconectar.setMinimumSize(new java.awt.Dimension(300, 40));
        btDesconectar.setPreferredSize(new java.awt.Dimension(300, 40));
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 222, 10, 222);
        pCentro.add(btDesconectar, gridBagConstraints);

        add(pCentro, java.awt.BorderLayout.CENTER);

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setPreferredSize(new java.awt.Dimension(638, 183));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbOrientador.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbOrientador.setForeground(new java.awt.Color(255, 255, 255));
        lbOrientador.setText("Secretária");

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbOrientador))
                .addGap(0, 656, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(lbOrientador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbClinica)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        MessagesAlert logout = new MessagesAlert();
        logout.MessageAlertDesconectarOpcoes();
    }//GEN-LAST:event_btDesconectarActionPerformed

    private void btCadastrarEstagiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarEstagiarioActionPerformed
        FormEstagiario form = new FormEstagiario();
        
        FormManager.showForm(form);
    }//GEN-LAST:event_btCadastrarEstagiarioActionPerformed

    private void btVisualizarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarAgendaActionPerformed
        FormAgenda form = new FormAgenda();
        FormManager.showForm(form);
    }//GEN-LAST:event_btVisualizarAgendaActionPerformed

    private void btCadastrarOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarOrientadorActionPerformed
        FormUsuario form = new FormUsuario();
        
        FormManager.showForm(form);
    }//GEN-LAST:event_btCadastrarOrientadorActionPerformed

    private void btCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarPacienteActionPerformed
        FormPaciente form = new FormPaciente();
        
        FormManager.showForm(form);
    }//GEN-LAST:event_btCadastrarPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarEstagiario;
    private javax.swing.JButton btCadastrarOrientador;
    private javax.swing.JButton btCadastrarPaciente;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JButton btVisualizarAgenda;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorth;
    // End of variables declaration//GEN-END:variables

}
