/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;
import Visao.Components.SimpleForm;
import Visao.JframeManager.FormManager;
import Visao.Utils.MessagesAlert;
import Visao.Utils.RedimencionarIcones;
import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author john
 */
public class MenuEstagiario extends SimpleForm {

    /**
     * Creates new form estagiarioMenu
     */
    public MenuEstagiario() {
        initComponents();
          // remove background customizado e volta ao default do L&F
        pCentro.putClientProperty(FlatClientProperties.STYLE, "background:null");
        
        RedimencionarIcones redimencionarIcone = new RedimencionarIcones();
        redimencionarIcone.redimensionarIcones(btGerenciarPacientes, "/Multimidia/imagens/gerenciarPacientesLogo.png",140);
        redimencionarIcone.redimensionarIcones(btAcessarProntuario, "/Multimidia/imagens/logoProntuario.png",130);
        redimencionarIcone.redimensionarIcones(btAgendarConsulta, "/Multimidia/imagens/logoAgenda.png",130);
        redimencionarIcone.redimensionarIcones(btAcessarListaEspera, "/Multimidia/imagens/gerenciarListas.png",115);
        redimencionarIcone.redimensionarIcones(btDesconectar, "/Multimidia/imagens/desconectar.png",130);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pCentro = new javax.swing.JPanel();
        btGerenciarPacientes = new javax.swing.JButton();
        btAgendarConsulta = new javax.swing.JButton();
        btAcessarProntuario = new javax.swing.JButton();
        btAcessarListaEspera = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbOrientador = new javax.swing.JLabel();
        lbLogoEstagiario = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(965, 607));
        setMinimumSize(new java.awt.Dimension(965, 607));
        setPreferredSize(new java.awt.Dimension(965, 607));
        setLayout(new java.awt.BorderLayout());

        pCentro.setBackground(java.awt.SystemColor.controlHighlight);
        pCentro.setLayout(new java.awt.GridBagLayout());

        btGerenciarPacientes.setBackground(new java.awt.Color(0, 114, 187));
        btGerenciarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btGerenciarPacientes.setForeground(new java.awt.Color(255, 255, 255));
        btGerenciarPacientes.setText("Gerenciar Pacientes");
        btGerenciarPacientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btGerenciarPacientes.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btGerenciarPacientes.setMaximumSize(new java.awt.Dimension(280, 60));
        btGerenciarPacientes.setMinimumSize(new java.awt.Dimension(280, 60));
        btGerenciarPacientes.setPreferredSize(new java.awt.Dimension(280, 60));
        btGerenciarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarPacientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btGerenciarPacientes, gridBagConstraints);

        btAgendarConsulta.setBackground(new java.awt.Color(140, 72, 67));
        btAgendarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAgendarConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btAgendarConsulta.setText("Agendar Consulta");
        btAgendarConsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAgendarConsulta.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btAgendarConsulta.setMaximumSize(new java.awt.Dimension(280, 60));
        btAgendarConsulta.setMinimumSize(new java.awt.Dimension(280, 60));
        btAgendarConsulta.setPreferredSize(new java.awt.Dimension(280, 60));
        btAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendarConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btAgendarConsulta, gridBagConstraints);

        btAcessarProntuario.setBackground(new java.awt.Color(86, 78, 88));
        btAcessarProntuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarProntuario.setForeground(new java.awt.Color(255, 255, 255));
        btAcessarProntuario.setText("Prontuário");
        btAcessarProntuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAcessarProntuario.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btAcessarProntuario.setMaximumSize(new java.awt.Dimension(280, 60));
        btAcessarProntuario.setMinimumSize(new java.awt.Dimension(280, 60));
        btAcessarProntuario.setPreferredSize(new java.awt.Dimension(280, 60));
        btAcessarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarProntuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btAcessarProntuario, gridBagConstraints);

        btAcessarListaEspera.setBackground(new java.awt.Color(115, 87, 81));
        btAcessarListaEspera.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarListaEspera.setForeground(new java.awt.Color(255, 255, 255));
        btAcessarListaEspera.setText("Listas de Espera");
        btAcessarListaEspera.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btAcessarListaEspera.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btAcessarListaEspera.setMaximumSize(new java.awt.Dimension(280, 60));
        btAcessarListaEspera.setMinimumSize(new java.awt.Dimension(280, 60));
        btAcessarListaEspera.setPreferredSize(new java.awt.Dimension(280, 60));
        btAcessarListaEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarListaEsperaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btAcessarListaEspera, gridBagConstraints);

        btDesconectar.setBackground(new java.awt.Color(255, 51, 51));
        btDesconectar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        btDesconectar.setText("Desconectar");
        btDesconectar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btDesconectar.setMargin(new java.awt.Insets(5, 10, 5, 10));
        btDesconectar.setMaximumSize(new java.awt.Dimension(160, 60));
        btDesconectar.setMinimumSize(new java.awt.Dimension(160, 60));
        btDesconectar.setPreferredSize(new java.awt.Dimension(160, 60));
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 10, 6);
        pCentro.add(btDesconectar, gridBagConstraints);

        add(pCentro, java.awt.BorderLayout.CENTER);

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setPreferredSize(new java.awt.Dimension(638, 183));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbOrientador.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbOrientador.setForeground(new java.awt.Color(255, 255, 255));
        lbOrientador.setText("Estagiário");

        lbLogoEstagiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/logoCapivasEstag_resized.png"))); // NOI18N

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogoEstagiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbOrientador))
                .addGap(0, 594, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogoEstagiario, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNorthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbOrientador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbClinica)
                .addGap(61, 61, 61))
        );

        add(pNorth, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        MessagesAlert logout = new MessagesAlert();
        logout.MessageAlertDesconectarOpcoes();
    }//GEN-LAST:event_btDesconectarActionPerformed

    private void btGerenciarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarPacientesActionPerformed
        TableListaPacientes form = new TableListaPacientes();
        
        FormManager.showForm(form);
    }//GEN-LAST:event_btGerenciarPacientesActionPerformed

    private void btAcessarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarProntuarioActionPerformed
        FormProntuario form = new FormProntuario();
        
        FormManager.showForm(form);
    }//GEN-LAST:event_btAcessarProntuarioActionPerformed

    private void btAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendarConsultaActionPerformed
        FormAgenda form = new FormAgenda();
        
        FormManager.showForm(form);
    }//GEN-LAST:event_btAgendarConsultaActionPerformed

    private void btAcessarListaEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarListaEsperaActionPerformed
          MessagesAlert.showChooseLista(choice -> {
            if (choice == 0) {
                FormManager.showForm(new TableListaEsperaGeral());
            } else if (choice == 1) {
                FormManager.showForm(new TableListaEsperaEspecifica());
            }
            // se choice == -1, o usuário fechou o popup sem escolher
        });
    }//GEN-LAST:event_btAcessarListaEsperaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessarListaEspera;
    private javax.swing.JButton btAcessarProntuario;
    private javax.swing.JButton btAgendarConsulta;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JButton btGerenciarPacientes;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbLogoEstagiario;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorth;
    // End of variables declaration//GEN-END:variables
   
}
