/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;

import Visao.Components.SimpleForm;
import Visao.JframeManager.FormManager;
import java.util.List;

import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

/**
 *
 * @author john
 */
public class PageProgressBar extends SimpleForm {

    private Runnable onComplete; 

    public PageProgressBar(Runnable onComplete) {
        this.onComplete = onComplete;
        initComponents();
        loadProgressBar();
    }

    private void loadProgressBar() {
        SwingWorker<Void, Integer> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws InterruptedException {
                for (int i = 0; i <= 100; i += 5) {
                    Thread.sleep(50); 
                    publish(i); 
                }
                return null;
            }

            @Override
            protected void process(List<Integer> chunks) {
                pbCarregando.setValue(chunks.get(chunks.size() - 1));
                lbCarregando.setText("Carregando" + (pbCarregando.getValue() % 2 == 0 ? ".." : "..."));
            }

            @Override
            protected void done() {
                SwingUtilities.invokeLater(() -> {
                    FormManager.getForms().undo(); 
                    if (onComplete != null) {
                        onComplete.run();
                    }
                });
            }
        };
        worker.execute();
    }

    private void close() {
        if (getParent() != null) {
            getParent().remove(this);
            getParent().revalidate();
            getParent().repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorth = new javax.swing.JPanel();
        lbCarregando = new javax.swing.JLabel();
        pbCarregando = new javax.swing.JProgressBar();
        lbLogo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setPreferredSize(new java.awt.Dimension(638, 183));

        lbCarregando.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbCarregando.setForeground(new java.awt.Color(255, 255, 255));
        lbCarregando.setText("Carregando...");

        pbCarregando.setStringPainted(true);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/cpan-small.png"))); // NOI18N

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(lbCarregando)
                .addGap(0, 466, Short.MAX_VALUE))
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(pbCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(lbLogo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lbLogo)
                .addGap(18, 18, 18)
                .addComponent(pbCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCarregando)
                .addGap(0, 456, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCarregando;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel pNorth;
    private javax.swing.JProgressBar pbCarregando;
    // End of variables declaration//GEN-END:variables
}
