/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;

import Services.ArticleData;
import Services.NewsApiService;
import Visao.Components.Carousel;
import Visao.Components.PanelTemplate;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author john
 */
public class PageWelcome extends PanelTemplate {

    private JPanel pSouth;
    private Carousel carousel;

    /**
     * Creates new form PageWelcome
     */
    public PageWelcome() {
        initComponents();
        //initCarousel();

    }

    private void initCarousel() {
        SwingUtilities.invokeLater(() -> {
            NewsApiService newsService = new NewsApiService();

            new Thread(() -> {
                List<ArticleData> artigos = newsService.fetchTopPsychologyHeadlines();

                SwingUtilities.invokeLater(() -> {
                    carousel = new Carousel(artigos); 
                    pSouth = new JPanel(new BorderLayout());
                    pSouth.setPreferredSize(new java.awt.Dimension(1024, 200));
                    pSouth.add(carousel, BorderLayout.CENTER);

                    add(pSouth, BorderLayout.SOUTH);
                    revalidate(); 
                    repaint();
                });
            }).start();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbOrientador = new javax.swing.JLabel();
        lbCpanLogo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(975, 630));
        setMinimumSize(new java.awt.Dimension(975, 630));
        setPreferredSize(new java.awt.Dimension(975, 630));
        setLayout(new java.awt.BorderLayout());

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setPreferredSize(new java.awt.Dimension(638, 183));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbOrientador.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbOrientador.setForeground(new java.awt.Color(255, 255, 255));
        lbOrientador.setText("Seja bem vindo, Usuário");

        lbCpanLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/imagemHome.png"))); // NOI18N

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(lbCpanLogo))
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(lbOrientador))
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(lbClinica)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lbCpanLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbOrientador)
                .addGap(18, 18, 18)
                .addComponent(lbClinica)
                .addGap(0, 323, Short.MAX_VALUE))
        );

        add(pNorth, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbCpanLogo;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JPanel pNorth;
    // End of variables declaration//GEN-END:variables
}
