/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;

import Regradenegocio.GrupoRN;
import Regradenegocio.GrupoXPacienteRN;
import Regradenegocio.PacienteRN;
import VO.GrupoVO;
import VO.GrupoXPacienteVO;
import VO.PacienteVO;
import Visao.Components.PanelTemplate;
import Visao.JframeManager.FormManager;
import Visao.Utils.MessagesAlert;
import Visao.Utils.RedimencionarIcones;

import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author otnie
 */
public class PageGrupos extends PanelTemplate {
    private final MessagesAlert messagesAlert;

    /**
     * Creates new form PageConfiguracoes
     */
    public PageGrupos() {
        initComponents();
        RedimencionarIcones redimencionarIcone = new RedimencionarIcones();

        redimencionarIcone.redimensionarIcones(btSalvar, "/Multimidia/imagens/approved-icon.png", 20);
        redimencionarIcone.redimensionarIcones(btEditar, "/Multimidia/imagens/editar-btn.png", 40);
        redimencionarIcone.redimensionarIcones(btCancelar, "/Multimidia/imagens/cancelar-btn.png", 40);

        // Ícone para o botão "Ver Pacientes do Grupo"
        redimencionarIcone.redimensionarIcones(btnListarPacientes, "/Multimidia/imagens/view.png", 40);

        // Ícone para os botões "Adicionar" (usando o mesmo ícone para ambos)
        redimencionarIcone.redimensionarIcones(btnAdicionarPaciente, "/Multimidia/imagens/add.png", 20);
        redimencionarIcone.redimensionarIcones(btnAdicionarEstagiario, "/Multimidia/imagens/add.png", 20);
        messagesAlert = new MessagesAlert();

        bloquearCampos();

        inicializarComboBoxPacientes();
        inicializarComboBoxGrupos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        pNorth = new javax.swing.JPanel();
        lbClinica = new javax.swing.JLabel();
        lbProntuario = new javax.swing.JLabel();
        lbLogoCriarGrupos = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        cbNome = new javax.swing.JComboBox<>();
        lbDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        cbAdicionarPaciente = new JComboBox<PacienteVO>();
        btnAdicionarPaciente = new javax.swing.JButton();
        cbAdicionarEstagiario = new javax.swing.JComboBox<>();
        btnAdicionarEstagiario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btEditar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btnListarPacientes = new javax.swing.JButton();
        lbNovoNome = new javax.swing.JLabel();
        tfNovoNome = new javax.swing.JTextField();

        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(950, 630));
        setMinimumSize(new java.awt.Dimension(950, 630));
        setPreferredSize(new java.awt.Dimension(950, 630));

        pNorth.setBackground(new java.awt.Color(0, 102, 102));
        pNorth.setMaximumSize(new java.awt.Dimension(638, 150));
        pNorth.setMinimumSize(new java.awt.Dimension(638, 150));

        lbClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbClinica.setForeground(new java.awt.Color(255, 255, 255));
        lbClinica.setText("Clínica de Psicologia");

        lbProntuario.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbProntuario.setForeground(new java.awt.Color(255, 255, 255));
        lbProntuario.setText("Grupos");

        lbLogoCriarGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/logoGpAdd.png"))); // NOI18N

        javax.swing.GroupLayout pNorthLayout = new javax.swing.GroupLayout(pNorth);
        pNorth.setLayout(pNorthLayout);
        pNorthLayout.setHorizontalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogoCriarGrupos)
                .addGap(18, 18, 18)
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClinica)
                    .addComponent(lbProntuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNorthLayout.setVerticalGroup(
            pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNorthLayout.createSequentialGroup()
                .addGroup(pNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLogoCriarGrupos))
                    .addGroup(pNorthLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lbProntuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbClinica)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(51, 51, 51));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 102, 102));
        lbNome.setText("Nome");

        cbNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeActionPerformed(evt);
            }
        });

        lbDescricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDescricao.setForeground(new java.awt.Color(0, 102, 102));
        lbDescricao.setText("Descrição");

        taDescricao.setColumns(20);
        taDescricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        taDescricao.setRows(5);
        jScrollPane1.setViewportView(taDescricao);

        cbAdicionarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnAdicionarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdicionarPaciente.setText("Adicionar");
        btnAdicionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPacienteActionPerformed(evt);
            }
        });

        cbAdicionarEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnAdicionarEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdicionarEstagiario.setText("Adicionar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Adicionar Paciente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Adicionar Estagiário");

        btEditar.setBackground(new java.awt.Color(255, 255, 51));
        btEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btEditar.setForeground(new java.awt.Color(51, 51, 51));
        btEditar.setText("Editar");
        btEditar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                btEditarComponentHidden(evt);
            }
        });
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btCancelar.setText("Cancelar");
        btCancelar.setMaximumSize(new java.awt.Dimension(108, 39));
        btCancelar.setMinimumSize(new java.awt.Dimension(108, 39));
        btCancelar.setPreferredSize(new java.awt.Dimension(108, 39));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btnListarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnListarPacientes.setText("Ver Pacientes do Grupo");
        btnListarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPacientesActionPerformed(evt);
            }
        });

        lbNovoNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNovoNome.setForeground(new java.awt.Color(0, 102, 102));
        lbNovoNome.setText("Novo nome");

        tfNovoNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pNorth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnListarPacientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbAdicionarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionarPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAdicionarEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionarEstagiario))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(290, 290, 290)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome)
                            .addComponent(cbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNovoNome))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pNorth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbNovoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarPacientes))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAdicionarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarPaciente)
                    .addComponent(btnAdicionarEstagiario)
                    .addComponent(cbAdicionarEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String novoNome = tfNovoNome.getText().trim();
        String novaDescricao = taDescricao.getText().trim();

        if (novoNome.isEmpty()) {
            messagesAlert.showErrorMessage("O nome do grupo não pode ficar em branco.");
            return;
        }

        GrupoVO vo = new GrupoVO();
        GrupoVO atual = (GrupoVO) cbNome.getSelectedItem();
        assert atual != null;
        vo.setId(atual.getId());
        vo.setNome(novoNome);
        vo.setDescricao(novaDescricao);

        new GrupoRN().salvar(vo);

        messagesAlert.showSuccessMessage("Grupo atualizado com sucesso!");

        // volta ao estado inicial
        bloquearCampos();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btnAdicionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPacienteActionPerformed
        try {
            GrupoVO grupoSelecionado = (GrupoVO) cbNome.getSelectedItem();
            PacienteVO pacienteSelecionado = (PacienteVO) cbAdicionarPaciente.getSelectedItem();

            if (grupoSelecionado == null || pacienteSelecionado == null) {
                messagesAlert.showErrorMessage("Selecione um grupo e um paciente.");
                return;
            }

            GrupoXPacienteVO vo = new GrupoXPacienteVO();
            vo.setGrupoId(grupoSelecionado.getId());
            vo.setPacienteId(pacienteSelecionado.getId());
            vo.setDataEntrada(LocalDate.now()); // ou algum campo específico, se houver

            GrupoXPacienteRN rn = new GrupoXPacienteRN();
            rn.salvar(vo);

            messagesAlert.showSuccessMessage("Paciente adicionado ao grupo com sucesso.");
            // Atualizar alguma lista visual, se necessário

        } catch (Exception ex) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erro ao adicionar paciente ao grupo", ex);
            messagesAlert.showErrorMessage("Erro ao adicionar paciente ao grupo.");
        }
    }//GEN-LAST:event_btnAdicionarPacienteActionPerformed

    private void cbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeActionPerformed
        GrupoVO selecionado = (GrupoVO) cbNome.getSelectedItem();
        if (selecionado != null) {
            taDescricao.setText(selecionado.getDescricao());
        } else {
            taDescricao.setText("");
        }
    }//GEN-LAST:event_cbNomeActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        FormManager.showForm(new PageGrupos());
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btnListarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPacientesActionPerformed
        listarPacientes();
    }//GEN-LAST:event_btnListarPacientesActionPerformed

    private void btEditarComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btEditarComponentHidden
        liberarEdicao();
    }//GEN-LAST:event_btEditarComponentHidden

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        liberarEdicao();
    }//GEN-LAST:event_btEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btnAdicionarEstagiario;
    private javax.swing.JButton btnAdicionarPaciente;
    private javax.swing.JButton btnListarPacientes;
    private javax.swing.JComboBox<String> cbAdicionarEstagiario;
    private JComboBox<PacienteVO> cbAdicionarPaciente;
    private javax.swing.JComboBox<GrupoVO> cbNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbClinica;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbLogoCriarGrupos;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNovoNome;
    private javax.swing.JLabel lbProntuario;
    private javax.swing.JPanel pNorth;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfNovoNome;
    // End of variables declaration//GEN-END:variables

    private void inicializarComboBoxPacientes() {
        /*
         * NOTA PARA FUTUROS DESENVOLVEDORES:
         * Este método é intencionalmente repetido e muito similar ao "inicializarComboBoxPacientes".
         * A duplicação foi mantida para facilitar uma futura implementação que poderá, por exemplo,
         * incluir o nome do responsável junto ao grupo, diferenciando a lógica de busca.
         *
         * Caso essa alteração específica não seja realizada, é altamente recomendável
         * refatorar ambos os métodos para uma única função genérica a fim de eliminar
         * a repetição de código.
         */
        try {
            PacienteRN pacienteRN = new PacienteRN();
            List<PacienteVO> pacientes = pacienteRN.listarPacientes();

            if (pacientes == null || pacientes.isEmpty()) {
                bloquearCampos();
                messagesAlert.showErrorMessage("Não há pacientes cadastrados no sistema.");
                return;
            }

            DefaultComboBoxModel<PacienteVO> modelo = new DefaultComboBoxModel<>();
            for (PacienteVO paciente : pacientes) {
                modelo.addElement(paciente);
            }

            cbAdicionarPaciente.setModel(modelo);
            cbAdicionarPaciente.setSelectedIndex(-1);

        } catch (Exception e) {
            messagesAlert.showErrorMessage("Erro ao carregar pacientes!");
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erro ao carregar pacientes", e);
        }
    }

    private void inicializarComboBoxGrupos() {
        try {
            GrupoRN grupoRN = new GrupoRN();
            List<GrupoVO> grupos = grupoRN.listarTodos();

            if (grupos == null || grupos.isEmpty()) {
                bloquearCampos();
                messagesAlert.showErrorMessage("Não há pacientes cadastrados no sistema.");
                return;
            }

            DefaultComboBoxModel<GrupoVO> modelo = new DefaultComboBoxModel<>();
            for (GrupoVO grupo : grupos) {
                modelo.addElement(grupo);
            }
            cbNome.setModel(modelo);
            cbNome.setSelectedIndex(-1);
        } catch (Exception e) {
            messagesAlert.showErrorMessage("Erro ao carregar grupos!");
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Erro ao carregar grupos", e);
        }
    }

    private void listarPacientes() {
        GrupoVO grupoSelecionado = (GrupoVO) cbNome.getSelectedItem();
        if (grupoSelecionado == null) {
            messagesAlert.showErrorMessage("Selecione um grupo primeiro.");
            return;
        }

        TableListaPacientesGrupo painel
                = new TableListaPacientesGrupo(
                        grupoSelecionado.getId(),
                        grupoSelecionado.getNome()
                );

        JFrame frame = new JFrame("Pacientes do Grupo: " + grupoSelecionado.getNome());
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        frame.setContentPane(painel);
        frame.pack();                  
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }
    
    private void liberarEdicao() {
        lbNovoNome.setVisible(true);
        tfNovoNome.setVisible(true);

        taDescricao.setEnabled(true);
        btSalvar.setEnabled(true);

        btEditar.setEnabled(false);
    }

    private void bloquearCampos() {
        lbNovoNome.setVisible(false);
        tfNovoNome.setVisible(false);
        btSalvar.setEnabled(false);
        taDescricao.setEnabled(false);
        btEditar.setEnabled(true);
    }
}
