/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;

import Visao.Components.PanelTemplate;
import Visao.JframeManager.FormManager;
import java.util.List;

import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import java.awt.Color;

/**
 *
 * @author john
 */
public class PageProgressBar extends PanelTemplate {

    private Runnable onComplete;
    private volatile boolean carregamentoPronto = false;

    public PageProgressBar(Runnable onComplete) {
        this.onComplete = onComplete;
        initComponents();

        setBackground(new Color(0, 102, 102));

        loadProgressBar();

    }

    private void loadProgressBar() {
        SwingWorker<Void, Integer> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                int progress = 0;

                // Executa o trabalho de forma assíncrona
                Thread tarefaThread = new Thread(() -> {
                    if (getOnComplete() != null) {
                        getOnComplete().run();
                    }
                    setCarregamentoPronto(true); 
                });
                tarefaThread.start();

                // Enquanto não estiver pronto, avança a barra
                while (!isCarregamentoPronto()) {
                    Thread.sleep(100);
                    progress = Math.min(progress + 1, 99);
                    publish(progress);
                }

                publish(100);
                return null;
            }

            @Override
            protected void process(List<Integer> chunks) {
                int value = chunks.get(chunks.size() - 1);
                pbCarregando.setValue(value);
                lbCarregando.setText("Carregando" + (value % 2 == 0 ? ".." : "..."));
            }

            @Override
            protected void done() {
                SwingUtilities.invokeLater(() -> {
                    FormManager.getForms().undo();
                });
            }
        };
        worker.execute();
    }

    private void close() {
        if (getParent() != null) {
            getParent().remove(this);
            getParent().revalidate();
            getParent().repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogoCapiva = new javax.swing.JLabel();
        pbCarregando = new javax.swing.JProgressBar();
        lbCarregando = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setMaximumSize(new java.awt.Dimension(2000, 2000));
        setMinimumSize(new java.awt.Dimension(975, 630));
        setPreferredSize(new java.awt.Dimension(975, 630));

        lbLogoCapiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimidia/imagens/capivaraLoading.gif"))); // NOI18N

        pbCarregando.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pbCarregando.setStringPainted(true);

        lbCarregando.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbCarregando.setForeground(new java.awt.Color(255, 255, 255));
        lbCarregando.setText("Carregando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(lbCarregando))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(lbLogoCapiva))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(pbCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(lbLogoCapiva)
                .addGap(18, 18, 18)
                .addComponent(pbCarregando, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCarregando)
                .addGap(192, 192, 192))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCarregando;
    private javax.swing.JLabel lbLogoCapiva;
    private javax.swing.JProgressBar pbCarregando;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the onComplete
     */
    public Runnable getOnComplete() {
        return onComplete;
    }

    /**
     * @param onComplete the onComplete to set
     */
    public void setOnComplete(Runnable onComplete) {
        this.onComplete = onComplete;
    }

    /**
     * @return the carregamentoPronto
     */
    public boolean isCarregamentoPronto() {
        return carregamentoPronto;
    }

    /**
     * @param carregamentoPronto the carregamentoPronto to set
     */
    public void setCarregamentoPronto(boolean carregamentoPronto) {
        this.carregamentoPronto = carregamentoPronto;
    }
}
