/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao.Telas;

import VO.UsuarioVO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.function.BiConsumer;

/**
 *
 * @author john
 */
public class PanelPermissoesPesquisador extends javax.swing.JPanel {

    /**
     * Creates new form FormPermissoesPesquisador
     */
    public PanelPermissoesPesquisador() {
        initComponents();
    }
    
    public HashMap<String, List<String>> obterOpcoesSelecionadas() {
        HashMap<String, List<String>> selecionados = new HashMap<>();

        // Helper para adicionar item à lista
        BiConsumer<String, String> adicionar = (chave, valor) -> {
            selecionados.computeIfAbsent(chave, k -> new ArrayList<>()).add(valor);
        };

        // Gráficos
        if (cbTotalPacientesAtivos.isSelected()) adicionar.accept("Gráfico", "Total de Pacientes Ativos");
        if (cbTaxaMediaComparecimento.isSelected()) adicionar.accept("Gráfico", "Taxa Média de Comparecimento");
        if (cbPacientesListaEspera.isSelected()) adicionar.accept("Gráfico", "Pacientes na Lista de Espera");
        if (cbTotalAtendimentosMes.isSelected()) adicionar.accept("Gráfico", "Total de Atendimentos (Mês Atual)");
        if (cbEstagiariosAtivos.isSelected()) adicionar.accept("Gráfico", "Estagiários Ativos");
        if (cbGenero.isSelected()) adicionar.accept("Gráfico", "Gênero");
        if (cbEstadoCivil.isSelected()) adicionar.accept("Gráfico", "Estado Civil");
        if (cbRaca.isSelected()) adicionar.accept("Gráfico", "Raça/Cor/Etnia");
        if (cbEvolucaoAtendimento.isSelected()) adicionar.accept("Gráfico", "Evolução Atendimentos");
        if (cbAgendadosRealizados.isSelected()) adicionar.accept("Gráfico", "Agendados vs Realizados");
        if (cbPacienteComparecimento.isSelected()) adicionar.accept("Gráfico", "Paciente Comparecimento");
        if (cbTempoMedio.isSelected()) adicionar.accept("Gráfico", "Tempo Médio Atendimento");
        if (cbPacienteIdade.isSelected()) adicionar.accept("Gráfico", "Paciente por Idade");
        if (cbListaEspera.isSelected()) adicionar.accept("Gráfico", "Lista de Espera");
        if (cbOcupacaoSala.isSelected()) adicionar.accept("Gráfico", "Ocupação das Salas");

        // Tabelas
        if (cbPacientesTabela.isSelected()) adicionar.accept("Tabelas", "Todos os Pacientes");
        if (cbListaEsperaTabela.isSelected()) adicionar.accept("Tabelas", "Lista de Espera Geral");
        if (cbListaEsperaEspecificaTabela.isSelected()) adicionar.accept("Tabelas", "Lista de Espera Específica");
        if (cbAgendamentosTabela.isSelected()) adicionar.accept("Tabelas", "Agendamentos");
        if (cbAtendimentosTabela.isSelected()) adicionar.accept("Tabelas", "Atendimentos");
        if (cbEstagiariosTabela.isSelected()) adicionar.accept("Tabelas", "Todos os Estagiários");
        if (cbUsuariosTabela.isSelected()) adicionar.accept("Tabelas", "Todos os Usuários");

        // Páginas
        if (cbPaginaAtendimento.isSelected()) adicionar.accept("Formulário", "Atendimento");
        if (cbPaginaCalendario.isSelected()) adicionar.accept("Formulário", "Calendário");
        if (cbPaginaVincular.isSelected()) adicionar.accept("Formulário", "Vincular Estagiário");
        if (cbPaginaUsuario.isSelected()) adicionar.accept("Formulário", "Usuário");
        if (cbPaginaProntuario.isSelected()) adicionar.accept("Formulário", "Prontuário");
        if (cbPaginaAgenda.isSelected()) adicionar.accept("Formulário", "Agenda");
        if (cbPaginaAgenda.isSelected()) adicionar.accept("Formulário", "Busca Avançada");

        return selecionados;
    }
    
    public void preencherDadosEdicao(UsuarioVO usuario){
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbGraficosPermissoes = new javax.swing.JLabel();
        cbGenero = new javax.swing.JCheckBox();
        cbEstadoCivil = new javax.swing.JCheckBox();
        cbRaca = new javax.swing.JCheckBox();
        cbEvolucaoAtendimento = new javax.swing.JCheckBox();
        cbAgendadosRealizados = new javax.swing.JCheckBox();
        cbPacienteComparecimento = new javax.swing.JCheckBox();
        cbTempoMedio = new javax.swing.JCheckBox();
        cbPacienteIdade = new javax.swing.JCheckBox();
        cbListaEspera = new javax.swing.JCheckBox();
        cbOcupacaoSala = new javax.swing.JCheckBox();
        cbTabelas = new javax.swing.JLabel();
        cbPacientesTabela = new javax.swing.JCheckBox();
        cbListaEsperaTabela = new javax.swing.JCheckBox();
        cbListaEsperaEspecificaTabela = new javax.swing.JCheckBox();
        cbAgendamentosTabela = new javax.swing.JCheckBox();
        cbAtendimentosTabela = new javax.swing.JCheckBox();
        cbEstagiariosTabela = new javax.swing.JCheckBox();
        cbUsuariosTabela = new javax.swing.JCheckBox();
        cbTabelas1 = new javax.swing.JLabel();
        cbPaginaAtendimento = new javax.swing.JCheckBox();
        cbPaginaCalendario = new javax.swing.JCheckBox();
        cbPaginaVincular = new javax.swing.JCheckBox();
        cbPaginaUsuario = new javax.swing.JCheckBox();
        cbPaginaProntuario = new javax.swing.JCheckBox();
        cbPaginaAgenda = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cbPacientesListaEspera = new javax.swing.JCheckBox();
        cbTotalAtendimentosMes = new javax.swing.JCheckBox();
        cbEstagiariosAtivos = new javax.swing.JCheckBox();
        cbTotalPacientesAtivos = new javax.swing.JCheckBox();
        cbTaxaMediaComparecimento = new javax.swing.JCheckBox();
        cbBuscaAvancada = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(950, 312));
        setMinimumSize(new java.awt.Dimension(950, 312));
        setPreferredSize(new java.awt.Dimension(950, 312));

        lbGraficosPermissoes.setText("Quais gráficos são permitidos?");

        cbGenero.setSelected(true);
        cbGenero.setText("Gênero");

        cbEstadoCivil.setSelected(true);
        cbEstadoCivil.setText("Estado Civil");

        cbRaca.setSelected(true);
        cbRaca.setText("Raça/Cor/Etnia");

        cbEvolucaoAtendimento.setSelected(true);
        cbEvolucaoAtendimento.setText("Evolução de Atendimentos");

        cbAgendadosRealizados.setSelected(true);
        cbAgendadosRealizados.setText("Atendimentos Agendados vs Realizados");

        cbPacienteComparecimento.setSelected(true);
        cbPacienteComparecimento.setText("Comparecimento do Paciente");

        cbTempoMedio.setSelected(true);
        cbTempoMedio.setText("Tempo Médio de Atendimento");

        cbPacienteIdade.setSelected(true);
        cbPacienteIdade.setText("Paciente por Idade");

        cbListaEspera.setSelected(true);
        cbListaEspera.setText("Lista de Espera");

        cbOcupacaoSala.setSelected(true);
        cbOcupacaoSala.setText("Ocupação de Sala");

        cbTabelas.setText("Quais Tabelas são permitidas?");

        cbPacientesTabela.setSelected(true);
        cbPacientesTabela.setText("Pacientes");

        cbListaEsperaTabela.setSelected(true);
        cbListaEsperaTabela.setText("Lista de Esperal Geral");

        cbListaEsperaEspecificaTabela.setSelected(true);
        cbListaEsperaEspecificaTabela.setText("Lista de Espera Específica");

        cbAgendamentosTabela.setSelected(true);
        cbAgendamentosTabela.setText("Agendamentos");

        cbAtendimentosTabela.setSelected(true);
        cbAtendimentosTabela.setText("Atendimentos");

        cbEstagiariosTabela.setSelected(true);
        cbEstagiariosTabela.setText("Estagiários");

        cbUsuariosTabela.setSelected(true);
        cbUsuariosTabela.setText("Usuários");

        cbTabelas1.setText("Quais Páginas são permitidas?");

        cbPaginaAtendimento.setSelected(true);
        cbPaginaAtendimento.setText("Atendimento");

        cbPaginaCalendario.setSelected(true);
        cbPaginaCalendario.setText("Calendário");

        cbPaginaVincular.setSelected(true);
        cbPaginaVincular.setText("Vincular Estagiário");

        cbPaginaUsuario.setSelected(true);
        cbPaginaUsuario.setText("Usuário");

        cbPaginaProntuario.setSelected(true);
        cbPaginaProntuario.setText("Prontuário");

        cbPaginaAgenda.setSelected(true);
        cbPaginaAgenda.setText("Agenda");

        cbPacientesListaEspera.setSelected(true);
        cbPacientesListaEspera.setText("Pacientes na Lista de Espera");

        cbTotalAtendimentosMes.setSelected(true);
        cbTotalAtendimentosMes.setText("Total de Atendimentos (Mês Atual)");

        cbEstagiariosAtivos.setSelected(true);
        cbEstagiariosAtivos.setText("Estagiários Ativos");

        cbTotalPacientesAtivos.setSelected(true);
        cbTotalPacientesAtivos.setText("Total de Pacientes Ativos");

        cbTaxaMediaComparecimento.setSelected(true);
        cbTaxaMediaComparecimento.setText("Taxa Média de Comparecimento");

        cbBuscaAvancada.setSelected(true);
        cbBuscaAvancada.setText("Busca Avançada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGraficosPermissoes)
                    .addComponent(cbTabelas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbListaEsperaTabela)
                        .addGap(18, 18, 18)
                        .addComponent(cbListaEsperaEspecificaTabela)
                        .addGap(18, 18, 18)
                        .addComponent(cbAgendamentosTabela)
                        .addGap(18, 18, 18)
                        .addComponent(cbAtendimentosTabela)
                        .addGap(18, 18, 18)
                        .addComponent(cbEstagiariosTabela)
                        .addGap(18, 18, 18)
                        .addComponent(cbPacientesTabela)
                        .addGap(18, 18, 18)
                        .addComponent(cbUsuariosTabela))
                    .addComponent(cbTabelas1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPaginaCalendario)
                        .addGap(18, 18, 18)
                        .addComponent(cbPaginaVincular)
                        .addGap(18, 18, 18)
                        .addComponent(cbPaginaUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(cbPaginaProntuario)
                        .addGap(18, 18, 18)
                        .addComponent(cbPaginaAgenda)
                        .addGap(18, 18, 18)
                        .addComponent(cbBuscaAvancada)
                        .addGap(18, 18, 18)
                        .addComponent(cbPaginaAtendimento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbTotalPacientesAtivos)
                        .addGap(18, 18, 18)
                        .addComponent(cbTaxaMediaComparecimento)
                        .addGap(18, 18, 18)
                        .addComponent(cbPacientesListaEspera)
                        .addGap(18, 18, 18)
                        .addComponent(cbTotalAtendimentosMes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbEstagiariosAtivos)
                        .addGap(18, 18, 18)
                        .addComponent(cbGenero)
                        .addGap(18, 18, 18)
                        .addComponent(cbEstadoCivil)
                        .addGap(18, 18, 18)
                        .addComponent(cbRaca)
                        .addGap(18, 18, 18)
                        .addComponent(cbEvolucaoAtendimento)
                        .addGap(18, 18, 18)
                        .addComponent(cbAgendadosRealizados))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbListaEspera)
                        .addGap(18, 18, 18)
                        .addComponent(cbOcupacaoSala)
                        .addGap(18, 18, 18)
                        .addComponent(cbTempoMedio)
                        .addGap(18, 18, 18)
                        .addComponent(cbPacienteIdade)
                        .addGap(18, 18, 18)
                        .addComponent(cbPacienteComparecimento)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGraficosPermissoes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTotalPacientesAtivos)
                    .addComponent(cbTaxaMediaComparecimento)
                    .addComponent(cbPacientesListaEspera)
                    .addComponent(cbTotalAtendimentosMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEstagiariosAtivos)
                    .addComponent(cbGenero)
                    .addComponent(cbEstadoCivil)
                    .addComponent(cbRaca)
                    .addComponent(cbEvolucaoAtendimento)
                    .addComponent(cbAgendadosRealizados))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbListaEspera)
                    .addComponent(cbOcupacaoSala)
                    .addComponent(cbTempoMedio)
                    .addComponent(cbPacienteIdade)
                    .addComponent(cbPacienteComparecimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTabelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbListaEsperaTabela)
                    .addComponent(cbListaEsperaEspecificaTabela)
                    .addComponent(cbAgendamentosTabela)
                    .addComponent(cbAtendimentosTabela)
                    .addComponent(cbEstagiariosTabela)
                    .addComponent(cbPacientesTabela)
                    .addComponent(cbUsuariosTabela))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTabelas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaginaCalendario)
                    .addComponent(cbPaginaVincular)
                    .addComponent(cbPaginaUsuario)
                    .addComponent(cbPaginaProntuario)
                    .addComponent(cbPaginaAgenda)
                    .addComponent(cbPaginaAtendimento)
                    .addComponent(cbBuscaAvancada))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAgendadosRealizados;
    private javax.swing.JCheckBox cbAgendamentosTabela;
    private javax.swing.JCheckBox cbAtendimentosTabela;
    private javax.swing.JCheckBox cbBuscaAvancada;
    private javax.swing.JCheckBox cbEstadoCivil;
    private javax.swing.JCheckBox cbEstagiariosAtivos;
    private javax.swing.JCheckBox cbEstagiariosTabela;
    private javax.swing.JCheckBox cbEvolucaoAtendimento;
    private javax.swing.JCheckBox cbGenero;
    private javax.swing.JCheckBox cbListaEspera;
    private javax.swing.JCheckBox cbListaEsperaEspecificaTabela;
    private javax.swing.JCheckBox cbListaEsperaTabela;
    private javax.swing.JCheckBox cbOcupacaoSala;
    private javax.swing.JCheckBox cbPacienteComparecimento;
    private javax.swing.JCheckBox cbPacienteIdade;
    private javax.swing.JCheckBox cbPacientesListaEspera;
    private javax.swing.JCheckBox cbPacientesTabela;
    private javax.swing.JCheckBox cbPaginaAgenda;
    private javax.swing.JCheckBox cbPaginaAtendimento;
    private javax.swing.JCheckBox cbPaginaCalendario;
    private javax.swing.JCheckBox cbPaginaProntuario;
    private javax.swing.JCheckBox cbPaginaUsuario;
    private javax.swing.JCheckBox cbPaginaVincular;
    private javax.swing.JCheckBox cbRaca;
    private javax.swing.JLabel cbTabelas;
    private javax.swing.JLabel cbTabelas1;
    private javax.swing.JCheckBox cbTaxaMediaComparecimento;
    private javax.swing.JCheckBox cbTempoMedio;
    private javax.swing.JCheckBox cbTotalAtendimentosMes;
    private javax.swing.JCheckBox cbTotalPacientesAtivos;
    private javax.swing.JCheckBox cbUsuariosTabela;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbGraficosPermissoes;
    // End of variables declaration//GEN-END:variables
}
