package visao;


import java.awt.Image;
import javax.swing.ImageIcon;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafael
 */
public class ExemploRedimensionamentoIcones extends javax.swing.JFrame {

    /**
     * Creates new form TelaOrientador
     */
    public ExemploRedimensionamentoIcones() {
        initComponents();
        setLocationRelativeTo(null);
        redimensionarIcones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btValidarRelato = new javax.swing.JButton();
        jlOrientador = new javax.swing.JLabel();
        btAtribuirPaciente = new javax.swing.JButton();
        btAcessarListaEsperaGeral = new javax.swing.JButton();
        btAcessarListaEsperaAtendidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orientador");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btValidarRelato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btValidarRelato.setText("Validar Relato");

        jlOrientador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlOrientador.setText("Orientador");

        btAtribuirPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAtribuirPaciente.setText("Atribuir Paciente");

        btAcessarListaEsperaGeral.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarListaEsperaGeral.setText("Acessar Lista de Espera Geral");

        btAcessarListaEsperaAtendidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarListaEsperaAtendidos.setText("Acessar Lista de Espera Atendidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btValidarRelato)
                                .addGap(171, 171, 171)
                                .addComponent(btAcessarListaEsperaGeral))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btAcessarListaEsperaAtendidos)
                                .addGap(81, 81, 81)
                                .addComponent(btAtribuirPaciente))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jlOrientador)))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlOrientador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btValidarRelato)
                    .addComponent(btAcessarListaEsperaGeral))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcessarListaEsperaAtendidos)
                    .addComponent(btAtribuirPaciente))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessarListaEsperaAtendidos;
    private javax.swing.JButton btAcessarListaEsperaGeral;
    private javax.swing.JButton btAtribuirPaciente;
    private javax.swing.JButton btValidarRelato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlOrientador;
    // End of variables declaration//GEN-END:variables
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemploRedimensionamentoIcones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemploRedimensionamentoIcones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemploRedimensionamentoIcones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemploRedimensionamentoIcones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExemploRedimensionamentoIcones().setVisible(true);
        });
    }
    private void redimensionarIcones() {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource("/imagens/edit.png"));
        Image iconeEmEscala = iconeOriginal.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btValidarRelato.setIcon(new ImageIcon(iconeEmEscala));
    }

   
}
