package visao;

import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafael
 */
public class TelaEstagiario extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstagiario
     */
    public TelaEstagiario() {
        initComponents();
        setLocationRelativeTo(null);
        redimensionarIcones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCentro = new javax.swing.JPanel();
        btGerenciarPacientes = new javax.swing.JButton();
        btAgendarConsulta = new javax.swing.JButton();
        btAcessarProntuario = new javax.swing.JButton();
        btProduzirRelato = new javax.swing.JButton();
        btAcessarListaEspera = new javax.swing.JButton();
        pNorte = new javax.swing.JPanel();
        jlEstagiario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estagiário");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        pCentro.setBackground(new java.awt.Color(255, 255, 255));

        btGerenciarPacientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btGerenciarPacientes.setText("Gerenciar Pacientes");

        btAgendarConsulta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAgendarConsulta.setText("Agendar Consulta");

        btAcessarProntuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarProntuario.setText("Acessar Prontuário");

        btProduzirRelato.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btProduzirRelato.setText("Produzir Relato");

        btAcessarListaEspera.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btAcessarListaEspera.setText("Acessar Lista de Espera");

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAgendarConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btGerenciarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                        .addGap(84, 84, 84)
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAcessarProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btProduzirRelato, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btAcessarListaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerenciarPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAcessarProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgendarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProduzirRelato, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btAcessarListaEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        getContentPane().add(pCentro, java.awt.BorderLayout.CENTER);

        pNorte.setBackground(new java.awt.Color(255, 255, 255));

        jlEstagiario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlEstagiario.setText("Estagiário");
        pNorte.add(jlEstagiario);

        getContentPane().add(pNorte, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstagiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstagiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessarListaEspera;
    private javax.swing.JButton btAcessarProntuario;
    private javax.swing.JButton btAgendarConsulta;
    private javax.swing.JButton btGerenciarPacientes;
    private javax.swing.JButton btProduzirRelato;
    private javax.swing.JLabel jlEstagiario;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorte;
    // End of variables declaration//GEN-END:variables
    
    private void redimensionarIcones(){
        
        //Gerenciar Pacientes
        ImageIcon iconeOriginalGerenciarPacientes = new ImageIcon(getClass().getResource("/imagens/imagem1.png"));
        Image iconeEmEscalaGerenciarPacientes = iconeOriginalGerenciarPacientes.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btGerenciarPacientes.setIcon(new ImageIcon(iconeEmEscalaGerenciarPacientes));
        
        //Acessar Prontuario
        ImageIcon iconeOriginalAcessarProntuario = new ImageIcon(getClass().getResource("/imagens/prontuario.png"));
        Image iconeEmEscalaAcessarProntuario = iconeOriginalAcessarProntuario.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btAcessarProntuario.setIcon(new ImageIcon(iconeEmEscalaAcessarProntuario));
        
        //Agendar Consulta
        ImageIcon iconeOriginalAgendarConsulta = new ImageIcon(getClass().getResource("/imagens/agendarConsulta.png"));
        Image iconeEmEscalaAgendarConsulta = iconeOriginalAgendarConsulta.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btAgendarConsulta.setIcon(new ImageIcon(iconeEmEscalaAgendarConsulta));
        //Produzir Relato
        ImageIcon iconeOriginalProduzirRelato = new ImageIcon(getClass().getResource("/imagens/edit.png"));
        Image iconeEmEscalaProduzirRelato = iconeOriginalProduzirRelato.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btProduzirRelato.setIcon(new ImageIcon(iconeEmEscalaProduzirRelato));

        //Acessar Lista de Espera
        ImageIcon iconeOriginalAcessarListaEspera = new ImageIcon(getClass().getResource("/imagens/listaEspera.png"));
        Image iconeEmEscalaAcessarListaEspera = iconeOriginalAcessarListaEspera.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        btAcessarListaEspera.setIcon(new ImageIcon(iconeEmEscalaAcessarListaEspera));
}
    }
   

