  package visao;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafael
 */
public class TelaCadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form TelaProntuario
     */
    public TelaCadastroPaciente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCentro = new javax.swing.JPanel();
        lbPaciente = new javax.swing.JLabel();
        tfPaciente = new javax.swing.JTextField();
        lbDataNascimento = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        lbCelular = new javax.swing.JLabel();
        lbContato2 = new javax.swing.JLabel();
        lbRua = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        lbResponsavel = new javax.swing.JLabel();
        tfResponsavel = new javax.swing.JTextField();
        lbEstagiario = new javax.swing.JLabel();
        tfEstagiario = new javax.swing.JTextField();
        lbOrientador = new javax.swing.JLabel();
        lbAtendido = new javax.swing.JLabel();
        cbAtendido = new javax.swing.JCheckBox();
        btEditar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        lbDisponibilidade = new javax.swing.JLabel();
        tfPeriodo = new javax.swing.JTextField();
        lbPeriodo = new javax.swing.JLabel();
        tfDisponibilidade = new javax.swing.JTextField();
        cbOrientador = new javax.swing.JComboBox<>();
        lbBairro = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        ftfDataNascimento = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        pNorte = new javax.swing.JPanel();
        lbCadastroPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Paciente");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        pCentro.setBackground(new java.awt.Color(255, 255, 255));
        pCentro.setPreferredSize(new java.awt.Dimension(1024, 768));

        lbPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPaciente.setText("*Paciente:");

        tfPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfPaciente.setText("João Pedro da Silva");

        lbDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDataNascimento.setText("*Data de Nascimento:");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbGenero.setText("*Gênero:");

        cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        cbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeneroActionPerformed(evt);
            }
        });

        lbCelular.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbCelular.setText("*Celular:");

        lbContato2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbContato2.setText("*Celular (Contato):");

        lbRua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbRua.setText("*Rua:");

        tfRua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfRua.setText("América");
        tfRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRuaActionPerformed(evt);
            }
        });

        lbResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbResponsavel.setText("Responsável:");

        tfResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfResponsavel.setText("Maria da Silva");

        lbEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEstagiario.setText("*Estagiário:");

        tfEstagiario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbOrientador.setText("*Orientador:");

        lbAtendido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbAtendido.setText("*Atendido:");

        cbAtendido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btEditar.setText("Editar");

        btSalvar.setBackground(new java.awt.Color(51, 153, 255));
        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btSalvar.setText("Salvar");

        lbDisponibilidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbDisponibilidade.setText("*Disponibilidade:");

        tfPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPeriodoActionPerformed(evt);
            }
        });

        lbPeriodo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbPeriodo.setText("*Período");

        tfDisponibilidade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        cbOrientador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbOrientador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bruna", "Pedro", "Maria" }));

        lbBairro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbBairro.setText("*Bairro:");

        tfBairro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfBairro.setText("Centro");

        lbNumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbNumero.setText("*Número:");

        tfNumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tfNumero.setText("80");

        ftfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ftfDataNascimento.setText("    /    /");
        ftfDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout pCentroLayout = new javax.swing.GroupLayout(pCentro);
        pCentro.setLayout(pCentroLayout);
        pCentroLayout.setHorizontalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDisponibilidade)
                            .addGroup(pCentroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbOrientador)
                                    .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pCentroLayout.createSequentialGroup()
                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPaciente))
                                .addGap(36, 36, 36)
                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDataNascimento)
                                    .addComponent(ftfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbResponsavel)))
                            .addGroup(pCentroLayout.createSequentialGroup()
                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pCentroLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbCelular)
                                    .addComponent(lbContato2))
                                .addGap(45, 45, 45)
                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pCentroLayout.createSequentialGroup()
                                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pCentroLayout.createSequentialGroup()
                                                .addComponent(lbBairro)
                                                .addGap(144, 144, 144)
                                                .addComponent(lbRua))
                                            .addGroup(pCentroLayout.createSequentialGroup()
                                                .addGap(221, 221, 221)
                                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbEstagiario)
                                                    .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbNumero)))
                                    .addGroup(pCentroLayout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(btEditar)
                                        .addGap(46, 46, 46)
                                        .addComponent(btSalvar))
                                    .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pCentroLayout.createSequentialGroup()
                                            .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(71, 71, 71)
                                            .addComponent(cbAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pCentroLayout.createSequentialGroup()
                                            .addComponent(lbGenero)
                                            .addGap(101, 101, 101)
                                            .addComponent(lbAtendido)))))
                            .addGroup(pCentroLayout.createSequentialGroup()
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPeriodo)
                                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        pCentroLayout.setVerticalGroup(
            pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCentroLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsavel)
                    .addComponent(lbDataNascimento)
                    .addComponent(lbPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCelular)
                    .addComponent(lbGenero)
                    .addComponent(lbAtendido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbAtendido, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairro)
                    .addComponent(lbRua)
                    .addComponent(lbNumero)
                    .addComponent(lbContato2))
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pCentroLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDisponibilidade)
                    .addComponent(lbPeriodo)
                    .addComponent(lbEstagiario))
                .addGap(39, 39, 39)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEstagiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lbOrientador)
                .addGap(18, 18, 18)
                .addComponent(cbOrientador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btSalvar))
                .addGap(14, 14, 14))
        );

        getContentPane().add(pCentro, java.awt.BorderLayout.CENTER);

        pNorte.setBackground(new java.awt.Color(255, 255, 255));

        lbCadastroPaciente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbCadastroPaciente.setText("Cadastro de Paciente");
        pNorte.add(lbCadastroPaciente);

        getContentPane().add(pNorte, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGeneroActionPerformed

    private void tfRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRuaActionPerformed

    private void tfPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox cbAtendido;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbOrientador;
    private javax.swing.JFormattedTextField ftfDataNascimento;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel lbAtendido;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCadastroPaciente;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbContato2;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbDisponibilidade;
    private javax.swing.JLabel lbEstagiario;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbOrientador;
    private javax.swing.JLabel lbPaciente;
    private javax.swing.JLabel lbPeriodo;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbRua;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pNorte;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfDisponibilidade;
    private javax.swing.JTextField tfEstagiario;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPaciente;
    private javax.swing.JTextField tfPeriodo;
    private javax.swing.JTextField tfResponsavel;
    private javax.swing.JTextField tfRua;
    // End of variables declaration//GEN-END:variables
}
